### ISSUE TITLE
CT Assertion failed: required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#10]
```
mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650532969107%22%2C%22timestamp%22%3A1650537510511%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:195:16)
at initializePhetioObject (PhetioObject.ts:167:11)
at (PhetioDataHandler.ts:107:4)
at (PhetioAction.ts:81:4)
at (PressListener.ts:334:24)
at (DragListener.ts:269:4)
at (PredictMeanNode.ts:47:27)
at (LevelingOutScreenView.ts:136:28)
at (LevelingOutScreen.ts:32:15)
id: Bayes Chrome
Snapshot from 4/21/2022, 3:22:49 AM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650532969107%22%2C%22timestamp%22%3A1650535796514%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:195:16)
at initializePhetioObject (PhetioObject.ts:167:11)
at (PhetioDataHandler.ts:107:4)
at (PhetioAction.ts:81:4)
at (PressListener.ts:334:24)
at (DragListener.ts:269:4)
at (PredictMeanNode.ts:47:27)
at (LevelingOutScreenView.ts:136:28)
at (LevelingOutScreen.ts:32:15)
id: Bayes Chrome
Snapshot from 4/21/2022, 3:22:49 AM

----------------------------------

mean-share-and-balance : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/studio/?sim=mean-share-and-balance&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650532969107%22%2C%22timestamp%22%3A1650534565587%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:195:16)
at initializePhetioObject (PhetioObject.ts:167:11)
at (PhetioDataHandler.ts:107:4)
at (PhetioAction.ts:81:4)
at (PressListener.ts:334:24)
at (DragListener.ts:269:4)
at (PredictMeanNode.ts:47:27)
at (LevelingOutScreenView.ts:136:28)
at (LevelingOutScreen.ts:32:15)
id: Bayes Chrome
Snapshot from 4/21/2022, 3:22:49 AM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance
3 out of 4 tests passed. 1 failed.
SimTests: mean-share-and-balance: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/assert/js/assert.js:28:13)
at PhetioAction.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/chipper/dist/js/tandem/js/PhetioObject.js:138:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/chipper/dist/js/tandem/js/PhetioObject.js:111:12)
at new PhetioDataHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/chipper/dist/js/tandem/js/PhetioDataHandler.js:65:5)
at new PhetioAction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/chipper/dist/js/tandem/js/PhetioAction.js:56:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/chipper/dist/js/scenery/js/listeners/PressListener.js:170:25)
at new DragListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/chipper/dist/js/scenery/js/listeners/DragListener.js:137:5)
at new PredictMeanNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/chipper/dist/js/mean-share-and-balance/js/leveling-out/view/PredictMeanNode.js:33:27)
at new LevelingOutScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/chipper/dist/js/mean-share-and-balance/js/leveling-out/view/LevelingOutScreenView.js:98:29)
at LevelingOutScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/chipper/dist/js/mean-share-and-balance/js/leveling-out/LevelingOutScreen.js:23:18)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650532969107/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:195:16)
at initializePhetioObject (PhetioObject.ts:167:11)
at (PhetioDataHandler.ts:107:4)
at (PhetioAction.ts:81:4)
at (PressListener.ts:334:24)
at (DragListener.ts:269:4)
at (PredictMeanNode.ts:47:27)
at (LevelingOutScreenView.ts:136:28)
at (LevelingOutScreen.ts:32:15)
id: Bayes Chrome
Snapshot from 4/21/2022, 3:22:49 AM
```

**Comment by samreid** [comment]
@marlitas indicated she was working on this today.  Reassigning.

**Comment by marlitas** [comment]
Required tandems added to predictMeanLine.

**Comment by KatieWoe** [comment]
This is still in CT. Reopening
```
mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1651012021700%22%2C%22timestamp%22%3A1651017811030%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:195:16)
at initializePhetioObject (PhetioObject.ts:167:11)
at (PhetioDataHandler.ts:99:4)
at (PhetioAction.ts:81:4)
at (PressListener.ts:335:24)
at (DragListener.ts:269:4)
at (WaterLevelTriangleNode.ts:56:27)
at (WaterCup3DNode.ts:80:31)
at (LevelingOutScreenView.ts:155:27)
id: Bayes Chrome
Snapshot from 4/26/2022, 4:27:01 PM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1651012021700%22%2C%22timestamp%22%3A1651034109672%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:195:16)
at initializePhetioObject (PhetioObject.ts:167:11)
at (PhetioDataHandler.ts:99:4)
at (PhetioAction.ts:81:4)
at (PressListener.ts:335:24)
at (DragListener.ts:269:4)
at (WaterLevelTriangleNode.ts:56:27)
at (WaterCup3DNode.ts:80:31)
at (LevelingOutScreenView.ts:155:27)
id: Bayes Chrome
Snapshot from 4/26/2022, 4:27:01 PM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1651012021700%22%2C%22timestamp%22%3A1651015268407%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:195:16)
at initializePhetioObject (PhetioObject.ts:167:11)
at (PhetioDataHandler.ts:99:4)
at (PhetioAction.ts:81:4)
at (PressListener.ts:335:24)
at (DragListener.ts:269:4)
at (WaterLevelTriangleNode.ts:56:27)
at (WaterCup3DNode.ts:80:31)
at (LevelingOutScreenView.ts:155:27)
id: Bayes Chrome
Snapshot from 4/26/2022, 4:27:01 PM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1651012021700%22%2C%22timestamp%22%3A1651034707857%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:195:16)
at initializePhetioObject (PhetioObject.ts:167:11)
at (PhetioDataHandler.ts:99:4)
at (PhetioAction.ts:81:4)
at (PressListener.ts:335:24)
at (DragListener.ts:269:4)
at (WaterLevelTriangleNode.ts:56:27)
at (WaterCup3DNode.ts:80:31)
at (LevelingOutScreenView.ts:155:27)
id: Bayes Chrome
Snapshot from 4/26/2022, 4:27:01 PM

----------------------------------

mean-share-and-balance : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/studio/?sim=mean-share-and-balance&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1651012021700%22%2C%22timestamp%22%3A1651017612222%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:195:16)
at initializePhetioObject (PhetioObject.ts:167:11)
at (PhetioDataHandler.ts:99:4)
at (PhetioAction.ts:81:4)
at (PressListener.ts:335:24)
at (DragListener.ts:269:4)
at (WaterLevelTriangleNode.ts:56:27)
at (WaterCup3DNode.ts:80:31)
at (LevelingOutScreenView.ts:155:27)
id: Bayes Chrome
Snapshot from 4/26/2022, 4:27:01 PM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance
3 out of 4 tests passed. 1 failed.
SimTests: mean-share-and-balance: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/assert/js/assert.js:28:13)
at PhetioAction.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/chipper/dist/js/tandem/js/PhetioObject.js:138:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/chipper/dist/js/tandem/js/PhetioObject.js:111:12)
at new PhetioDataHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/chipper/dist/js/tandem/js/PhetioDataHandler.js:65:5)
at new PhetioAction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/chipper/dist/js/tandem/js/PhetioAction.js:56:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/chipper/dist/js/scenery/js/listeners/PressListener.js:170:25)
at new DragListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/chipper/dist/js/scenery/js/listeners/DragListener.js:137:5)
at new WaterLevelTriangleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/chipper/dist/js/mean-share-and-balance/js/leveling-out/view/WaterLevelTriangleNode.js:35:27)
at new WaterCup3DNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/chipper/dist/js/mean-share-and-balance/js/leveling-out/view/WaterCup3DNode.js:56:32)
at new LevelingOutScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/chipper/dist/js/mean-share-and-balance/js/leveling-out/view/LevelingOutScreenView.js:114:28)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651012021700/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:195:16)
at initializePhetioObject (PhetioObject.ts:167:11)
at (PhetioDataHandler.ts:99:4)
at (PhetioAction.ts:81:4)
at (PressListener.ts:335:24)
at (DragListener.ts:269:4)
at (WaterLevelTriangleNode.ts:56:27)
at (WaterCup3DNode.ts:80:31)
at (LevelingOutScreenView.ts:155:27)
id: Bayes Chrome
Snapshot from 4/26/2022, 4:27:01 PM
```

**Comment by marlitas** [comment]
Ahh this is for a new element just added today. I will make sure to add tandems in before pushing new code up.

**Comment by marlitas** [comment]
This error is no longer appearing in CT. Closing.
