### ISSUE TITLE
CT phetioID already registered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#11]
```
mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651591565278/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1651591565278%22%2C%22timestamp%22%3A1651593502051%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: meanShareAndBalance.levelingOutScreen.view.waterCup3DNode.waterLevelTriangle.waterLevelVSlider.thumbNode
Error: Assertion failed: phetioID already registered: meanShareAndBalance.levelingOutScreen.view.waterCup3DNode.waterLevelTriangle.waterLevelVSlider.thumbNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651591565278/assert/js/assert.js:28:13)
at assert (phetioEngine.js:645:35)
at phetioObjectAdded (phetioEngine.js:1238:19)
at addPhetioObject (Tandem.js:175:37)
at addPhetioObject (PhetioObject.ts:328:16)
at initializePhetioObject (Node.ts:6011:10)
at initializePhetioObject (Node.ts:5988:9)
at mutate (Path.ts:85:9)
at (WaterLevelTriangleNode.ts:42:31)
at (WaterCup3DNode.ts:102:31)
id: Bayes Chrome
Snapshot from 5/3/2022, 9:26:05 AM
```

**Comment by marlitas** [comment]
This error is no longer appearing in CT. Closing.
