### ISSUE TITLE
CT Incorrect Tandem suffix

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#116]
```
mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663642258128%22%2C%22timestamp%22%3A1663647466571%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:357:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:228:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:123:9)
at (IntroControlPanel.ts:35:30)
at createNode (GroupItemOptions.ts:44:18)
at Array.map
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663642258128%22%2C%22timestamp%22%3A1663654429605%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:357:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:228:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:123:9)
at (IntroControlPanel.ts:35:30)
at createNode (GroupItemOptions.ts:44:18)
at Array.map
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663642258128%22%2C%22timestamp%22%3A1663671202078%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:357:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:228:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:123:9)
at (IntroControlPanel.ts:35:30)
at createNode (GroupItemOptions.ts:44:18)
at Array.map
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663642258128%22%2C%22timestamp%22%3A1663654470539%7D
Uncaught Error: Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:357:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:228:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:123:9)
at (IntroControlPanel.ts:35:30)
at createNode (GroupItemOptions.ts:44:18)
at Array.map
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663642258128%22%2C%22timestamp%22%3A1663671221047%7D
Uncaught Error: Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:357:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:228:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:123:9)
at (IntroControlPanel.ts:35:30)
at createNode (GroupItemOptions.ts:44:18)
at Array.map
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM

----------------------------------

mean-share-and-balance : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/studio/?sim=mean-share-and-balance&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663642258128%22%2C%22timestamp%22%3A1663647847069%7D
Uncaught Error: Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:357:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:228:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:123:9)
at (IntroControlPanel.ts:35:30)
at createNode (GroupItemOptions.ts:44:18)
at Array.map
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM

----------------------------------

mean-share-and-balance : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/studio/?sim=mean-share-and-balance&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663642258128%22%2C%22timestamp%22%3A1663654282074%7D
Uncaught Error: Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:357:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:228:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:123:9)
at (IntroControlPanel.ts:35:30)
at createNode (GroupItemOptions.ts:44:18)
at Array.map
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM

----------------------------------

mean-share-and-balance : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/studio/?sim=mean-share-and-balance&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663642258128%22%2C%22timestamp%22%3A1663669281286%7D
Uncaught Error: Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:357:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:228:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:123:9)
at (IntroControlPanel.ts:35:30)
at createNode (GroupItemOptions.ts:44:18)
at Array.map
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true
32 out of 33 tests passed. 1 failed.
SimTests: mean-share-and-balance: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/tandem/js/PhetioObject.js:276:17)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/scenery/js/nodes/Node.js:6368:11)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/scenery/js/nodes/Text.js:196:11)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/scenery/js/nodes/Node.js:6358:10)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/scenery/js/nodes/Text.js:88:18)
at new Text (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/scenery/js/nodes/Text.js:77:10)
at Object.createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/mean-share-and-balance/js/intro/view/IntroControlPanel.js:26:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/sun/js/GroupItemOptions.js:20:19
at Array.map (<anonymous>)

Uncaught Error: Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckboxError: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:357:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:228:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:123:9)
at (IntroControlPanel.ts:35:30)
at createNode (GroupItemOptions.ts:44:18)
at Array.map
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance
30 out of 31 tests passed. 1 failed.
SimTests: mean-share-and-balance: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/tandem/js/PhetioObject.js:276:17)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/scenery/js/nodes/Node.js:6368:11)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/scenery/js/nodes/Text.js:196:11)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/scenery/js/nodes/Node.js:6358:10)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/scenery/js/nodes/Text.js:88:18)
at new Text (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/scenery/js/nodes/Text.js:77:10)
at Object.createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/mean-share-and-balance/js/intro/view/IntroControlPanel.js:26:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/chipper/dist/js/sun/js/GroupItemOptions.js:20:19
at Array.map (<anonymous>)

Uncaught Error: Uncaught Error: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckboxError: Assertion failed: Incorrect Tandem suffix, expected = Text. actual = meanShareAndBalance.introScreen.view.controlPanel.introOptionsCheckboxGroup.predictMeanCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:357:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:228:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:123:9)
at (IntroControlPanel.ts:35:30)
at createNode (GroupItemOptions.ts:44:18)
at Array.map
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM
```

**Comment by marlitas** [comment]
This looks fixed in CT. Closing.
