### ISSUE TITLE
CT reentry detected, value=1.0534356008388628, oldValue=1.0804753024681668

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#118]
```
mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665033643982%22%2C%22timestamp%22%3A1665038826667%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=1.0534356008388628, oldValue=1.0804753024681668
Error: Assertion failed: reentry detected, value=1.0534356008388628, oldValue=1.0804753024681668
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:304:14)
at _notifyListeners (ReadOnlyProperty.ts:258:13)
at unguardedSet (ReadOnlyProperty.ts:242:11)
at set (Property.ts:65:10)
at set (IntroModel.ts:260:31)
at callback (IntroModel.ts:280:6)
at iterateCups (IntroModel.ts:228:9)
at stepWaterLevels (IntroModel.ts:289:9)
at step (Sim.ts:432:21)
id: Bayes Puppeteer
Snapshot from 10/5/2022, 11:20:43 PM

----------------------------------

mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665033643982%22%2C%22timestamp%22%3A1665056978842%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=-0.040158365262022704, oldValue=-0.055162589645635585
Error: Assertion failed: reentry detected, value=-0.040158365262022704, oldValue=-0.055162589645635585
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:304:14)
at _notifyListeners (ReadOnlyProperty.ts:258:13)
at unguardedSet (ReadOnlyProperty.ts:242:11)
at set (Property.ts:65:10)
at set (IntroModel.ts:260:31)
at callback (IntroModel.ts:280:6)
at iterateCups (IntroModel.ts:228:9)
at stepWaterLevels (IntroModel.ts:289:9)
at step (Sim.ts:432:21)
id: Bayes Puppeteer
Snapshot from 10/5/2022, 11:20:43 PM

----------------------------------

mean-share-and-balance : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1665033643982%22%2C%22timestamp%22%3A1665054047172%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[0]: Number must be within rangeProperty value.: value failed isValidValue: 1.0000297683933124
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (ReadOnlyProperty.ts:205:33)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:307:22)
at _notifyListeners (ReadOnlyProperty.ts:258:13)
at unguardedSet (ReadOnlyProperty.ts:242:11)
at set (Property.ts:65:10)
at set (IntroModel.ts:260:31)
at callback (IntroModel.ts:280:6)
id: Bayes Puppeteer
Snapshot from 10/5/2022, 11:20:43 PM

----------------------------------

mean-share-and-balance : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665033643982%22%2C%22timestamp%22%3A1665057534092%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: reentry detected, value=1.0073354905337228, oldValue=1.0095019307431643
Error: Assertion failed: reentry detected, value=1.0073354905337228, oldValue=1.0095019307431643
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:304:14)
at _notifyListeners (ReadOnlyProperty.ts:258:13)
at unguardedSet (ReadOnlyProperty.ts:242:11)
at set (Property.ts:65:10)
at set (IntroModel.ts:260:31)
at callback (IntroModel.ts:280:6)
at iterateCups (IntroModel.ts:228:9)
at stepWaterLevels (IntroModel.ts:289:9)
at step (Sim.ts:432:21)
id: Bayes Puppeteer
Snapshot from 10/5/2022, 11:20:43 PM

----------------------------------

mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665033643982%22%2C%22timestamp%22%3A1665057989974%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[0]: Number must be within rangeProperty value.: value failed isValidValue: 1.0000451510258914
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (ReadOnlyProperty.ts:205:33)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:307:22)
at _notifyListeners (ReadOnlyProperty.ts:258:13)
at unguardedSet (ReadOnlyProperty.ts:242:11)
at set (Property.ts:65:10)
at set (IntroModel.ts:260:31)
at callback (IntroModel.ts:280:6)
id: Bayes Puppeteer
Snapshot from 10/5/2022, 11:20:43 PM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665033643982%22%2C%22timestamp%22%3A1665043364586%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=0.998717658107392, oldValue=0.998198958016
Error: Assertion failed: reentry detected, value=0.998717658107392, oldValue=0.998198958016
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:304:14)
at _notifyListeners (ReadOnlyProperty.ts:258:13)
at unguardedSet (ReadOnlyProperty.ts:242:11)
at set (Property.ts:65:10)
at set (IntroModel.ts:260:31)
at callback (IntroModel.ts:280:6)
at iterateCups (IntroModel.ts:228:9)
at stepWaterLevels (IntroModel.ts:289:9)
at step (Sim.ts:432:21)
id: Bayes Puppeteer
Snapshot from 10/5/2022, 11:20:43 PM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665033643982%22%2C%22timestamp%22%3A1665057386653%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=0.628, oldValue=1.5
Error: Assertion failed: reentry detected, value=0.628, oldValue=1.5
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:304:14)
at _notifyListeners (ReadOnlyProperty.ts:258:13)
at unguardedSet (ReadOnlyProperty.ts:242:11)
at set (Property.ts:65:10)
at set (IntroModel.ts:260:31)
at callback (IntroModel.ts:280:6)
at iterateCups (IntroModel.ts:228:9)
at stepWaterLevels (IntroModel.ts:289:9)
at step (Sim.ts:432:21)
id: Bayes Puppeteer
Snapshot from 10/5/2022, 11:20:43 PM

----------------------------------

mean-share-and-balance : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1665033643982%22%2C%22timestamp%22%3A1665038912183%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=-0.0009996099755768691, oldValue=-0.0016549834032729624
Error: Assertion failed: reentry detected, value=-0.0009996099755768691, oldValue=-0.0016549834032729624
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665033643982/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:304:14)
at _notifyListeners (ReadOnlyProperty.ts:258:13)
at unguardedSet (ReadOnlyProperty.ts:242:11)
at set (Property.ts:65:10)
at set (IntroModel.ts:260:31)
at callback (IntroModel.ts:280:6)
at iterateCups (IntroModel.ts:228:9)
at stepWaterLevels (IntroModel.ts:289:9)
at step (Sim.ts:432:21)
id: Bayes Puppeteer
Snapshot from 10/5/2022, 11:20:43 PM
```

**Comment by marlitas** [comment]
This has been addressed and is no longer appearing on CT. Closing.
