### ISSUE TITLE
CT Build failed with status code 1:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#121]
```
mean-share-and-balance : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 54509ms
Building runnable repository (mean-share-and-balance, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 12505ms
>> Production minification complete: 101401ms (2430356 bytes)
>> Debug minification complete: 0ms (20987673 bytes)
Building brand: phet-io
>> Webpack build complete: 9636ms
>> Production minification complete: 86682ms (2448067 bytes)
>> Debug minification complete: 94389ms (2755085 bytes)
No migration rules found at ../chipper/dist/js/phet-io-sim-specific/repos/mean-share-and-balance/js/mean-share-and-balance-migration-rules.js, no rules to be bundled with phet-io.js.
No client guides found at ../phet-io-sim-specific/repos/mean-share-and-balance/client-guide/, no guides being built.
>> tsc complete: 11452ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1665482170673/chipper/js/grunt/copySupplementalPhetioFiles.js:361:5)
at async module.exports (/data/share/phet/continuous-testing/ct-snapshots/1665482170673/chipper/js/grunt/buildRunnable.js:357:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1665482170673/chipper/js/grunt/Gruntfile.js:287:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1665482170673/chipper/js/grunt/Gruntfile.js:65:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.

Error in fulfilling chunk Promise: [Error: TypeError: Converting circular structure to JSON
--> starting at object with constructor 'e'
| property 'parentTandem' -> object with constructor 'e'
| property 'children' -> object with constructor 'Object'
--- property 'isActiveProperty' closes the circle
at JSON.stringify (<anonymous>)
at http://localhost:46768/mean-share-and-balance/build/phet-io/mean-share-and-balance_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:960:370191
at i.value (http://localhost:46768/mean-share-and-balance/build/phet-io/mean-share-and-balance_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:960:41791)
at i.value (http://localhost:46768/mean-share-and-balance/build/phet-io/mean-share-and-balance_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:960:35054)
at i.value (http://localhost:46768/mean-share-and-balance/build/phet-io/mean-share-and-balance_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:960:34452)
at i.value (http://localhost:46768/mean-share-and-balance/build/phet-io/mean-share-and-balance_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:960:34234)
at i.set (http://localhost:46768/mean-share-and-balance/build/phet-io/mean-share-and-balance_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:960:31413)
at http://localhost:46768/mean-share-and-balance/build/phet-io/mean-share-and-balance_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:960:1716027]
Snapshot from 10/11/2022, 3:56:10 AM
```

**Comment by marlitas** [comment]
This looks to be fixed in a commit from yesterday in: https://github.com/phetsims/mean-share-and-balance/issues/52 . Closing
