### ISSUE TITLE
CT All descendants must be disposed by the next frame: 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#13]
```
mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652176480009/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652176480009%22%2C%22timestamp%22%3A1652178399404%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: meanShareAndBalance.levelingOutScreen.model.waterCup3DGroup.waterCup3D_1.waterLevelProperty
Error: Assertion failed: All descendants must be disposed by the next frame: meanShareAndBalance.levelingOutScreen.model.waterCup3DGroup.waterCup3D_1.waterLevelProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652176480009/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:637:18)
at Array.forEach
at forEach (PhetioObject.ts:636:18)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:93:8)
at emit (Sim.ts:963:24)
id: Bayes Chrome
Snapshot from 5/10/2022, 3:54:40 AM
```

**Comment by marlitas** [comment]
Error no longer appearing in CT. Closing.

**Comment by KatieWoe** [comment]
This is occurring again:
```
mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1655400805358%22%2C%22timestamp%22%3A1655404638219%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: meanShareAndBalance.levelingOutScreen.view.pipeNodeGroup.pipeNode_0.valveNode
Error: Assertion failed: All descendants must be disposed by the next frame: meanShareAndBalance.levelingOutScreen.view.pipeNodeGroup.pipeNode_0.valveNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:640:18)
at Array.forEach
at forEach (PhetioObject.ts:639:18)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:94:8)
at emit (Sim.ts:960:24)
id: Bayes Puppeteer
Snapshot from 6/16/2022, 11:33:25 AM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1655400805358%22%2C%22timestamp%22%3A1655403750197%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: meanShareAndBalance.levelingOutScreen.view.pipeNodeGroup.pipeNode_1.valveNode
Error: Assertion failed: All descendants must be disposed by the next frame: meanShareAndBalance.levelingOutScreen.view.pipeNodeGroup.pipeNode_1.valveNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:640:18)
at Array.forEach
at forEach (PhetioObject.ts:639:18)
at listener (Timer.ts:33:10)
at (TinyEmitter.ts:108:42)
at emit (Sim.ts:960:24)
id: Bayes Puppeteer
Snapshot from 6/16/2022, 11:33:25 AM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true
100 out of 102 tests passed. 2 failed.
SimTests: mean-share-and-balance: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: index out of bounds: 0, array length is 0
Error: Assertion failed: index out of bounds: 0, array length is 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/assert/js/assert.js:28:13)
at PhetioGroup.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/tandem/js/PhetioGroup.js:123:15)
at IntroModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/mean-share-and-balance/js/intro/model/IntroModel.js:208:42)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/joist/js/Sim.js:299:22
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/tandem/js/PhetioAction.js:91:17)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/joist/js/Sim.js:766:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/joist/js/Sim.js:755:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/joist/js/Sim.js:733:12)

SimTests: mean-share-and-balance: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: index out of bounds: 0, array length is 0
Error: Assertion failed: index out of bounds: 0, array length is 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/assert/js/assert.js:28:13)
at PhetioGroup.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/tandem/js/PhetioGroup.js:123:15)
at IntroModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/mean-share-and-balance/js/intro/model/IntroModel.js:208:42)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/joist/js/Sim.js:299:22
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/tandem/js/PhetioAction.js:91:17)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/joist/js/Sim.js:766:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/joist/js/Sim.js:755:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/chipper/dist/js/joist/js/Sim.js:733:12)

Uncaught Error: Uncaught Error: Assertion failed: index out of bounds: 0, array length is 0Error: Assertion failed: index out of bounds: 0, array length is 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/assert/js/assert.js:28:13)
at assert (PhetioGroup.ts:143:14)
at getElement (IntroModel.ts:240:41)
at step (Sim.ts:447:21)
at apply (PhetioAction.ts:125:16)
at execute (Sim.ts:990:30)
at stepSimulation (Sim.ts:980:11)
at stepOneFrame (Sim.ts:955:11)
id: Bayes Puppeteer
Snapshot from 6/16/2022, 11:33:25 AM
```

**Comment by samreid** [comment]
@marlitas and I fixed the problem in the commit.  Thanks!  Closing.
