### ISSUE TITLE
CT stateObject provided a public key that is not in the schema: position

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#132]
```
mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1674713901436%22%2C%22timestamp%22%3A1674718748142%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: stateObject provided a public key that is not in the schema: position
Error: Assertion failed: stateObject provided a public key that is not in the schema: position
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/assert/js/assert.js:28:13)
at assert (IOType.ts:425:30)
at check (IOType.ts:429:85)
at Array.forEach
at forEach (IOType.ts:429:69)
at isStateObjectValid (IOType.ts:413:37)
at isStateObjectValid (IOType.ts:444:9)
at validateStateObject (IOType.ts:281:23)
at toStateObject (PhetioStateEngine.ts:118:48)
at getValueJSON (PhetioStateEngine.ts:176:33)
id: Bayes Puppeteer
Snapshot from 1/25/2023, 11:18:21 PM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1674713901436%22%2C%22timestamp%22%3A1674728835104%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: stateObject provided a public key that is not in the schema: position
Error: Assertion failed: stateObject provided a public key that is not in the schema: position
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/assert/js/assert.js:28:13)
at assert (IOType.ts:425:30)
at check (IOType.ts:429:85)
at Array.forEach
at forEach (IOType.ts:429:69)
at isStateObjectValid (IOType.ts:413:37)
at isStateObjectValid (IOType.ts:444:9)
at validateStateObject (IOType.ts:281:23)
at toStateObject (PhetioStateEngine.ts:118:48)
at getValueJSON (PhetioStateEngine.ts:176:33)
id: Bayes Puppeteer
Snapshot from 1/25/2023, 11:18:21 PM
```

**Comment by zepumph** [comment]
https://github.com/phetsims/tandem/issues/290

**Comment by zepumph** [comment]
I'll take a look

**Comment by zepumph** [comment]
Easy fix now that the assertion is working . @marlitas will you give it a double check please?

**Comment by marlitas** [comment]
Looks reasonable. Closing!
