### ISSUE TITLE
CT required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#135]
Also in perennial and tandem
```
mean-share-and-balance : phet-io-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1687866632094%22%2C%22timestamp%22%3A1687866839140%7D&ea&brand=phet-io&phetioStandalone&fuzz
Query: ea&brand=phet-io&phetioStandalone&fuzz
Error: Assertion failed: required tandems must be supplied
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/assert/js/assert.js:28:13)
at providedOptions (PhetioObject.ts:204:14)
at initializePhetioObject (PhetioObject.ts:184:11)
at (PhetioDataHandler.ts:102:4)
at (Emitter.ts:44:4)
at (PushButtonModel.ts:75:24)
at (RectangularPushButton.ts:51:28)
at (CloseButton.ts:61:4)
at (Dialog.ts:241:24)
at (MeanCalculationDialog.ts:67:4)
at (LevelingOutScreenView.ts:142:34)
at (LevelingOutScreen.ts:33:15)
at createView (Screen.ts:307:22)
at initializeView (Sim.ts:868:15)
at (Sim.ts:876:25)
at (Sim.ts:874:16)
at i (Sim.ts:890:21)
at (Sim.ts:874:16)
at i (Sim.ts:890:21)
at (Sim.ts:874:16)
at i (Sim.ts:890:21)
at (Sim.ts:874:16)
at i (Sim.ts:890:21)
at (Sim.ts:874:16)
at i (Sim.ts:890:21)
at (Sim.ts:874:16)
at (Sim.ts:967:13)
at start (mean-share-and-balance-main.ts:37:6)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:56:42)
at forEach (asyncLoader.ts:56:21)
at proceedIfReady (asyncLoader.ts:69:11)
at image (logo_png.ts:6:0)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1687866632094%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1687866632094%22%2C%22timestamp%22%3A1687866839140%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1687866632094%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1687866632094%22%2C%22timestamp%22%3A1687866839140%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1687866632094%22%2C%22timestamp%22%3A1687866839140%7D&ea&brand=phet-io&phetioStandalone&fuzz
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/chipper/dist/js/scenery/js/util/Utils.js" line: 443}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/chipper/dist/js/scenery/js/util/Utils.js" line: 443}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/chipper/dist/js/scenery/js/util/Utils.js" line: 443}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/chipper/dist/js/scenery/js/util/Utils.js" line: 443}]
[CONSOLE] Assertion failed: required tandems must be supplied
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: required tandems must be supplied

id: "Sparky Node Firefox"
Snapshot from 6/27/2023, 5:50:32 AM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : assert
Tried to run 3 times, never completed, failure: Error: Error: Did not get next-test message in 400000ms: ["mean-share-and-balance","phet-io-wrappers-tests","assert"]
[URL] http://127.0.0.1/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1687866632094%2Fphet-io-wrappers%2Fphet-io-wrappers-tests.html%3Fsim%3Dmean-share-and-balance%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=600000&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-wrappers-tests%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1687866632094%22%2C%22timestamp%22%3A1687868180399%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1687866632094%2Fphet-io-wrappers%2Fphet-io-wrappers-tests.html%3Fsim%3Dmean-share-and-balance%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=600000&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-wrappers-tests%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1687866632094%22%2C%22timestamp%22%3A1687868180399%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true
[CONSOLE] enabling assert
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/mean-share-and-balance/mean-share-and-balance_en.html?brand=phet-io&ea&debugger&postMessageOnError
[CONSOLE] enabling assert
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/mean-share-and-balance/mean-share-and-balance_en.html?brand=phet-io&ea&debugger&postMessageOnError
[CONSOLE] enabling assert
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/mean-share-and-balance/mean-share-and-balance_en.html?brand=phet-io&ea&debugger&postMessageOnError
[CONSOLE] enabling assert
[CONSOLE] Assertion failed: args should be an array
[CONSOLE] Assertion failed: callback should be a function
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/mean-share-and-balance/mean-share-and-balance_en.html?brand=phet-io&postMessageOnError&sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&ea
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/chipper/dist/js/scenery/js/util/Utils.js" line: 443}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/chipper/dist/js/scenery/js/util/Utils.js" line: 443}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/chipper/dist/js/scenery/js/util/Utils.js" line: 443}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1687866632094/chipper/dist/js/scenery/js/util/Utils.js" line: 443}]
[CONSOLE] Assertion failed: required tandems must be supplied
[PAGE ERROR] Error: Assertion failed: required tandems must be supplied
[PAGE ERROR] Error: Error: Assertion failed: required tandems must be supplied

id: "Sparky Node Firefox"
Snapshot from 6/27/2023, 5:50:32 AM
```

**Comment by samreid** [comment]
I put a band-aid on for now, unassigning.

**Comment by marlitas** [comment]
Will look at this when MSaB is up for development again.

**Comment by marlitas** [comment]
This was handled in the above commit. Ready to close!
