### ISSUE TITLE
CT There is no top chocolate on plate since active chocolates is: 0

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#136]
```
mean-share-and-balance : phet-io-state-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1690880437306/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1690880437306%22%2C%22timestamp%22%3A1690880758211%7D
Error: Assertion failed: There is no top chocolate on plate since active chocolates is: 0
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1690880437306/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1690880437306/assert/js/assert.js:28:13)
at assert (LevelingOutModel.ts:214:14)
at getTopActiveChocolateOnPlate (LevelingOutModel.ts:300:13)
at personChocolateAmountDecrease (LevelingOutModel.ts:158:17)
at (TinyEmitter.ts:122:18)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:363:46)
at listener (PropertyStateHandler.ts:281:40)
at attemptToApplyPhases (PropertyStateHandler.ts:201:11)
at undeferAndNotifyProperties (PropertyStateHandler.ts:96:11)
at (TinyEmitter.ts:122:18)
at emit (Emitter.ts:61:21)
at emit (PhetioStateEngine.ts:273:25)
at setState (PhetioStateEngine.ts:284:9)
at setFullState (phetioEngine.ts:1063:64)
at apply (phetioCommandProcessor.ts:420:50)
at processCommand (phetioCommandProcessor.ts:298:35)
at getReturn (phetioCommandProcessor.ts:302:15)
at map (phetioCommandProcessor.ts:296:29)
at processCommands (phetioCommandProcessor.ts:238:15)
at addEventListener (phetioCommandProcessor.ts:193:11)
at (phetioCommandProcessor.ts:536:31)
id: Sparky Playwright Firefox
Snapshot from 8/1/2023, 3:00:37 AM
```

**Comment by marlitas** [comment]
Interesting... this sim hasn't been worked on in a while so I'm curious as to why this is popping up now. I'll take a look later today, but if it get's too tricky may not have time to resolve.

**Comment by marlitas** [comment]
I fuzzed for ten minutes straight (with fuzzPointers=2) and I was not able to replicate this error that CT is getting. My assumption is that this is an in between property states error. I'm not seeing it as frequently on CT as I saw it earlier... This seems like it might be up for investigation when we come back to MSaB, but I'll keep an eye on it for the next couple of days.

**Comment by samreid** [comment]
This is still happening regularly on CT, and may not be easy to solve. I don't know if it's in scope for my upcoming iteration. Self-unassigning for now.

**Comment by samreid** [comment]
Rather than letting CT continue to report this error, I feel we should track this error in this issue. So I converted the assertion failure to a console.log that refers to this issue. I'll mark as blocks-sim-publication so we don't accidentally publish with this defect.

**Comment by zepumph** [comment]
- [ ] Could we `console.error`?
- [ ] Could we prefix with something for consistency, like "SILENCED ASSERTION:"

**Comment by samreid** [comment]
Today @marlitas @zepumph and @jbphet reviewed the strategy above, and agreed it may be appropriate for certain cases. 
 We liked @zepumph additional recommendations, and I committed them for this case.

**Comment by pixelzoom** [comment]
This error occurred in CT 12/16/2023, 4:19:31 AM.

```
mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702728824260%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Uncaught Error: Assertion failed: There is no inactive bottom chocolate on plate since inactive chocolates is: 0
Error: Assertion failed: There is no inactive bottom chocolate on plate since inactive chocolates is: 0
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/assert/js/assert.js:28:13)
at assert (LevelingOutModel.ts:221:14)
at getBottomInactiveChocolateOnPlate (LevelingOutScreenView.ts:92:47)
at chocolateBarDropped (DraggableChocolate.ts:74:8)
at _end (DragListener.ts:381:24)
at callback (PressListener.ts:752:16)
at apply (PhetioAction.ts:162:16)
at execute (PressListener.ts:508:24)
at release (DragListener.ts:377:10)
at release (PressListener.ts:851:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1702725571789%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702728824260%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1702725571789%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702728824260%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702728824260%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: There is no inactive bottom chocolate on plate since inactive chocolates is: 0
[PAGE ERROR] Error: Error: Assertion failed: There is no inactive bottom chocolate on plate since inactive chocolates is: 0
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/assert/js/assert.js:28:13)
at LevelingOutModel.getBottomInactiveChocolateOnPlate (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/mean-share-and-balance/js/leveling-out/model/LevelingOutModel.js:171:15)
at chocolateBarDropped (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/mean-share-and-balance/js/leveling-out/view/LevelingOutScreenView.js:77:48)
at DragListener.end [as _end] (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/mean-share-and-balance/js/leveling-out/view/DraggableChocolate.js:52:9)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/scenery/js/listeners/DragListener.js:248:25
at DragListener.onRelease (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/scenery/js/listeners/PressListener.js:549:17)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/tandem/js/PhetioAction.js:133:17)
at DragListener.release (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/scenery/js/listeners/PressListener.js:325:25)
at DragListener.release (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/scenery/js/listeners/DragListener.js:244:11)
at DragListener.pointerUp (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/scenery/js/listeners/PressListener.js:639:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: There is no inactive bottom chocolate on plate since inactive chocolates is: 0
[PAGE ERROR] Error: Error: Assertion failed: There is no inactive bottom chocolate on plate since inactive chocolates is: 0
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/assert/js/assert.js:28:13)
at LevelingOutModel.getBottomInactiveChocolateOnPlate (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/mean-share-and-balance/js/leveling-out/model/LevelingOutModel.js:171:15)
at chocolateBarDropped (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/mean-share-and-balance/js/leveling-out/view/LevelingOutScreenView.js:77:48)
at DragListener.end [as _end] (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/mean-share-and-balance/js/leveling-out/view/DraggableChocolate.js:52:9)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/scenery/js/listeners/DragListener.js:248:25
at DragListener.onRelease (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/scenery/js/listeners/PressListener.js:549:17)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/tandem/js/PhetioAction.js:133:17)
at DragListener.release (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/scenery/js/listeners/PressListener.js:325:25)
at DragListener.release (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/scenery/js/listeners/DragListener.js:244:11)
at DragListener.pointerUp (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/scenery/js/listeners/PressListener.js:639:12)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 12/16/2023, 4:19:31 AM
```

**Comment by jbphet** [comment]
@marlitas and I are resuming work on this sim, so we have removed the workaround and will attempt to address the root of the problem if and when it reappears on CT.

**Comment by jbphet** [comment]
@marlitas and I did some investigation on this, and we made a change that improved the situation (the fuzz test would go for longer before hitting an assertion), but it then starting hitting a different assertion.  Rather than play whack-a-mole, we decided to turn off phet-io state testing until the model is further along.

**Comment by marlitas** [comment]
Putting on-hold until we are ready to turn phetio-state on again.

**Comment by marlitas** [comment]
I turned on state testing for this sim again. Will keep an eye out and see if this issue returns.

**Comment by marlitas** [comment]
I'm not seeing this error on CT anymore since the refactor. Closing.
