### ISSUE TITLE
CT Cannot read properties of undefined (reading 'valueProperty')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#153]
```
mean-share-and-balance : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1708445027344%22%2C%22timestamp%22%3A1708446427611%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught TypeError: Cannot read properties of undefined (reading 'valueProperty')
TypeError: Cannot read properties of undefined (reading 'valueProperty')
at valueProperty (BalancePointSceneModel.ts:88:35)
at regressLine (BalancePointSceneModel.ts:72:13)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:334:22)
at _notifyListeners (ReadOnlyProperty.ts:281:13)
at unguardedSet (ReadOnlyProperty.ts:265:11)
at set (Property.ts:65:10)
at set (NumberSpinner.ts:160:27)
at listener (TinyEmitter.ts:123:8)
at emit (Emitter.ts:62:21)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1708445027344%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1708445027344%22%2C%22timestamp%22%3A1708446427611%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1708445027344%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1708445027344%22%2C%22timestamp%22%3A1708446427611%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1708445027344%22%2C%22timestamp%22%3A1708446427611%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 593802
[CONSOLE] continuous-test-load
[PAGE ERROR] Error: TypeError: Cannot read properties of undefined (reading 'valueProperty')
at BalancePointSceneModel.regressLine (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/mean-share-and-balance/js/balance-point/model/BalancePointSceneModel.js:57:36)
at http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/mean-share-and-balance/js/balance-point/model/BalancePointSceneModel.js:45:14
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/ReadOnlyProperty.js:256:23)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/ReadOnlyProperty.js:205:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:12)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/Property.js:58:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/sun/js/NumberSpinner.js:90:166
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/Emitter.js:51:22)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 2/20/2024, 9:03:47 AM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1708445027344%22%2C%22timestamp%22%3A1708446213253%7D&ea&brand=phet-io&phetioStandalone&fuzz
Query: ea&brand=phet-io&phetioStandalone&fuzz
Uncaught Error: Assertion failed: stateObject is not valid for x. stateObject=

schema=
NumberIO
Error: Assertion failed: stateObject is not valid for x. stateObject=
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/assert/js/assert.js:28:13)
at assert (StateSchema.ts:233:36)
at Array.forEach
at forEach (StateSchema.ts:223:11)
at checkStateObjectValid (IOType.ts:432:42)
at isStateObjectValid (IOType.ts:465:9)
at validateStateObject (IOType.ts:283:23)
at toStateObject (ReadOnlyProperty.ts:324:34)
at getData (PhetioObject.ts:486:45)
at phetioStartEvent (ReadOnlyProperty.ts:319:66)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1708445027344%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1708445027344%22%2C%22timestamp%22%3A1708446213253%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1708445027344%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1708445027344%22%2C%22timestamp%22%3A1708446213253%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1708445027344%22%2C%22timestamp%22%3A1708446213253%7D&ea&brand=phet-io&phetioStandalone&fuzz
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: stateObject is not valid for x. stateObject= schema= JSHandle@object
[PAGE ERROR] Error: Error: Assertion failed: stateObject is not valid for x. stateObject=

schema=
NumberIO
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/tandem/js/types/StateSchema.js:182:37
at Array.forEach (<anonymous>)
at StateSchema.checkStateObjectValid (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/tandem/js/types/StateSchema.js:175:12)
at IOType.isStateObjectValid (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/tandem/js/types/IOType.js:262:43)
at IOType.validateStateObject (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/tandem/js/types/IOType.js:292:10)
at IOType.toStateObject (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/tandem/js/types/IOType.js:133:24)
at Object.getData (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/ReadOnlyProperty.js:248:35)
at Vector2Property.phetioStartEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/tandem/js/PhetioObject.js:414:46)
at Vector2Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/ReadOnlyProperty.js:243:67)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=-1, oldValue=0
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=-1, oldValue=0
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/assert/js/assert.js:28:13)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/ReadOnlyProperty.js:254:15)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/ReadOnlyProperty.js:205:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:12)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/Property.js:58:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/sun/js/NumberSpinner.js:90:166
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/Emitter.js:51:22)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/sun/js/buttons/PushButtonModel.js:146:23)
at CallbackTimer.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1708445027344/chipper/dist/js/axon/js/CallbackTimer.js:93:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 2/20/2024, 9:03:47 AM
```

**Comment by marlitas** [comment]
CT seems clear after the above commits. Closing.
