### ISSUE TITLE
CT There is an issue with the licenses for media types

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#158]
```
mean-share-and-balance : build
Build failed with status code 1:
Running "report-media" task
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1709503880926/mean-share-and-balance/images/greenApple.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1709503880926/mean-share-and-balance/images/labDesk.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1709503880926/mean-share-and-balance/images/notepadRing.svg
Fatal error: There is an issue with the licenses for media types.
Snapshot from 3/3/2024, 3:11:20 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzz-fuzzBoard-combo : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709503880926%22%2C%22timestamp%22%3A1709504423307%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard
Uncaught Error: Assertion failed: Should be a finite Vector2
Error: Assertion failed: Should be a finite Vector2
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/assert/js/assert.js:28:13)
at assert (Node.ts:2686:16)
at setTranslation (NotepadAppleNode.ts:70:50)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:328:22)
at _notifyListeners (ReadOnlyProperty.ts:275:13)
at unguardedSet (ReadOnlyProperty.ts:259:11)
at set (Property.ts:54:10)
at (FairShareModel.ts:201:51)
at baseTimes (http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/sherpa/lib/lodash-4.17.4.js:997:23)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1709503880926%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26supportsInteractiveDescription%3Dtrue%26fuzz%26fuzzBoard&duration=40000&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709503880926%22%2C%22timestamp%22%3A1709504423307%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1709503880926%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26supportsInteractiveDescription%3Dtrue%26fuzz%26fuzzBoard&duration=40000&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709503880926%22%2C%22timestamp%22%3A1709504423307%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709503880926%22%2C%22timestamp%22%3A1709504423307%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: Should be a finite Vector2
[PAGE ERROR] Error: Error: Assertion failed: Should be a finite Vector2
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/assert/js/assert.js:28:13)
at NotepadAppleNode.setTranslation (http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/scenery/js/nodes/Node.js:2442:17)
at http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/mean-share-and-balance/js/fair-share/view/NotepadAppleNode.js:48:50
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/axon/js/ReadOnlyProperty.js:253:23)
at Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/axon/js/ReadOnlyProperty.js:202:14)
at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/axon/js/Property.js:48:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/mean-share-and-balance/js/fair-share/model/FairShareModel.js:155:53
at baseTimes (http://128.138.93.172/continuous-testing/ct-snapshots/1709503880926/sherpa/lib/lodash-4.17.4.js:997:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 3/3/2024, 3:11:20 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1709503880926/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709503880926%22%2C%22timestamp%22%3A1709505299295%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true
Error: Assertion failed: Should be a finite Vector2
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1709503880926/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1709503880926/assert/js/assert.js:28:13)
at assert (Node.ts:2686:16)
at setTranslation (NotepadAppleNode.ts:70:50)
at (TinyEmitter.ts:123:18)
at emit (ReadOnlyProperty.ts:328:22)
at _notifyListeners (ReadOnlyProperty.ts:275:13)
at unguardedSet (ReadOnlyProperty.ts:259:11)
at set (Property.ts:54:10)
at (FairShareModel.ts:201:54)
at baseTimes (http://127.0.0.1/continuous-testing/ct-snapshots/1709503880926/sherpa/lib/lodash-4.17.4.js:997:23)
at times (http://127.0.0.1/continuous-testing/ct-snapshots/1709503880926/sherpa/lib/lodash-4.17.4.js:16095:29)
at times (FairShareModel.ts:196:16)
at (TinyEmitter.ts:123:18)
at emit (Emitter.ts:62:21)
at emit (Snack.ts:118:61)
at (TinyEmitter.ts:123:18)
at emit (Emitter.ts:62:21)
at emit (Animation.ts:331:25)
at (TinyEmitter.ts:137:42)
at emit (Sim.ts:413:16)
at apply (PhetioAction.ts:162:16)
at execute (Sim.ts:1023:30)
at stepSimulation (Sim.ts:1013:11)
at stepOneFrame (Sim.ts:988:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1709503880926%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26supportsInteractiveDescription%3Dtrue&duration=40000&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709503880926%22%2C%22timestamp%22%3A1709505299295%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1709503880926%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26supportsInteractiveDescription%3Dtrue&duration=40000&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709503880926%22%2C%22timestamp%22%3A1709505299295%7D
[ATTACHED]
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1709503880926/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709503880926%22%2C%22timestamp%22%3A1709505299295%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1709503880926/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: Should be a finite Vector2
[CONSOLE] Assertion failed: reentry detected, value=Vector2(-160.5, -112.975), oldValue=Vector2(-Infinity, 0)
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: Should be a finite Vector2
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=Vector2(-160.5, -112.975), oldValue=Vector2(-Infinity, 0)
[CONSOLE] Assertion failed: reentry detected, value=0, oldValue=1
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=0, oldValue=1
[CONSOLE] Assertion failed: reentry detected, value=1, oldValue=0
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=1, oldValue=0
[CONSOLE] Assertion failed: reentry detected, value=2, oldValue=1
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=2, oldValue=1

id: "Sparky Node Firefox"
Snapshot from 3/3/2024, 3:11:20 PM
```

**Comment by marlitas** [comment]
This was fixed in https://github.com/phetsims/mean-share-and-balance/issues/156. Thanks!
