### ISSUE TITLE
CT This PhetioObject has already been disposed, and cannot be disposed again

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#16]
```
mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652694771593%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:176:18)
at dispose (LevelingOutScreenView.ts:172:17)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PhetioDynamicElementContainer.ts:363:34)
at disposeElement (PhetioGroup.ts:117:10)
at disposeElement (LevelingOutModel.ts:132:29)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM

----------------------------------

mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652716289858%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:176:18)
at dispose (LevelingOutScreenView.ts:172:17)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PhetioDynamicElementContainer.ts:363:34)
at disposeElement (PhetioGroup.ts:117:10)
at disposeElement (LevelingOutModel.ts:132:29)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM

----------------------------------

mean-share-and-balance : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652713207875%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:176:18)
at dispose (LevelingOutScreenView.ts:172:17)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PhetioDynamicElementContainer.ts:363:34)
at disposeElement (PhetioGroup.ts:117:10)
at disposeElement (LevelingOutModel.ts:132:29)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM

----------------------------------

mean-share-and-balance : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652695287252%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:176:18)
at dispose (LevelingOutScreenView.ts:172:17)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PhetioDynamicElementContainer.ts:363:34)
at disposeElement (PhetioGroup.ts:117:10)
at disposeElement (LevelingOutModel.ts:132:29)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM

----------------------------------

mean-share-and-balance : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652694495747%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:176:18)
at dispose (LevelingOutScreenView.ts:172:17)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PhetioDynamicElementContainer.ts:363:34)
at disposeElement (PhetioGroup.ts:117:10)
at disposeElement (LevelingOutModel.ts:132:29)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM

----------------------------------

mean-share-and-balance : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652715949554%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:176:18)
at dispose (LevelingOutScreenView.ts:172:17)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PhetioDynamicElementContainer.ts:363:34)
at disposeElement (PhetioGroup.ts:117:10)
at disposeElement (LevelingOutModel.ts:132:29)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM

----------------------------------

mean-share-and-balance : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652694349368%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:176:18)
at dispose (LevelingOutScreenView.ts:172:17)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PhetioDynamicElementContainer.ts:363:34)
at disposeElement (PhetioGroup.ts:117:10)
at disposeElement (LevelingOutModel.ts:132:29)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM

----------------------------------

mean-share-and-balance : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652694411105%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:176:18)
at dispose (LevelingOutScreenView.ts:172:17)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PhetioDynamicElementContainer.ts:363:34)
at disposeElement (PhetioGroup.ts:117:10)
at disposeElement (LevelingOutModel.ts:132:29)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM

----------------------------------

mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652696104227%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:176:18)
at dispose (LevelingOutScreenView.ts:172:17)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PhetioDynamicElementContainer.ts:363:34)
at disposeElement (PhetioGroup.ts:117:10)
at disposeElement (LevelingOutModel.ts:132:29)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM

----------------------------------

mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652715958614%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
Error: Assertion failed: This PhetioObject has already been disposed, and cannot be disposed again
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:176:18)
at dispose (LevelingOutScreenView.ts:172:17)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PhetioDynamicElementContainer.ts:363:34)
at disposeElement (PhetioGroup.ts:117:10)
at disposeElement (LevelingOutModel.ts:132:29)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652694308081%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: dynamic element container expected its created instance's phetioType to match its parameterType.
Error: Assertion failed: dynamic element container expected its created instance's phetioType to match its parameterType.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:283:16)
at createDynamicElement (PhetioGroup.ts:268:30)
at createIndexedElement (PhetioGroup.ts:239:16)
at createNextElement (LevelingOutModel.ts:114:46)
at listener (Property.ts:381:4)
at link (LevelingOutModel.ts:107:30)
at (LevelingOutScreen.ts:29:12)
at createModel (Screen.ts:275:23)
at initializeModel (Sim.ts:841:15)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance
3 out of 4 tests passed. 1 failed.
SimTests: mean-share-and-balance: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: dynamic element container expected its created instance's phetioType to match its parameterType.
Error: Assertion failed: dynamic element container expected its created instance's phetioType to match its parameterType.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at PhetioGroup.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/chipper/dist/js/tandem/js/PhetioDynamicElementContainer.js:223:17)
at PhetioGroup.createIndexedElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/chipper/dist/js/tandem/js/PhetioGroup.js:264:31)
at PhetioGroup.createNextElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/chipper/dist/js/tandem/js/PhetioGroup.js:240:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/chipper/dist/js/mean-share-and-balance/js/leveling-out/model/LevelingOutModel.js:90:47
at NumberProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/chipper/dist/js/axon/js/Property.js:325:5)
at new LevelingOutModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/chipper/dist/js/mean-share-and-balance/js/leveling-out/model/LevelingOutModel.js:86:31)
at LevelingOutScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/chipper/dist/js/mean-share-and-balance/js/leveling-out/LevelingOutScreen.js:20:17)
at LevelingOutScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/chipper/dist/js/joist/js/Screen.js:196:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/chipper/dist/js/joist/js/Sim.js:631:16)

Uncaught Error: Uncaught Error: Assertion failed: dynamic element container expected its created instance's phetioType to match its parameterType.Error: Assertion failed: dynamic element container expected its created instance's phetioType to match its parameterType.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:283:16)
at createDynamicElement (PhetioGroup.ts:268:30)
at createIndexedElement (PhetioGroup.ts:239:16)
at createNextElement (LevelingOutModel.ts:114:46)
at listener (Property.ts:381:4)
at link (LevelingOutModel.ts:107:30)
at (LevelingOutScreen.ts:29:12)
at createModel (Screen.ts:275:23)
at initializeModel (Sim.ts:841:15)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM
```

**Comment by marlitas** [comment]
This error is no longer appearing in CT. Closing.
