### ISSUE TITLE
CT Cannot read properties of undefined (reading 'valueProperty')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#192]
```
mean-share-and-balance : multitouch-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711551508723%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'valueProperty')
TypeError: Cannot read properties of undefined (reading 'valueProperty')
at valueProperty (BalancePointSceneModel.ts:182:35)
at regressLine (BalancePointSceneModel.ts:112:60)
at baseTimes (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:16095:20)
at times (BalancePointSceneModel.ts:112:10)
at listener (TinyEmitter.ts:213:6)
at notifyLoop (TinyEmitter.ts:185:17)
at emit (ReadOnlyProperty.ts:336:22)
at _notifyListeners (ReadOnlyProperty.ts:283:13)
at unguardedSet (ReadOnlyProperty.ts:267:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1711550099591%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dfalse&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711551508723%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1711550099591%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dfalse&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711551508723%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711551508723%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[PAGE ERROR] Error: TypeError: Cannot read properties of undefined (reading 'valueProperty')
at BalancePointSceneModel.regressLine (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/mean-share-and-balance/js/balance-point/model/BalancePointSceneModel.js:116:36)
at http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/mean-share-and-balance/js/balance-point/model/BalancePointSceneModel.js:72:60
at baseTimes (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:16095:20)
at http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/mean-share-and-balance/js/balance-point/model/BalancePointSceneModel.js:72:11
at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/ReadOnlyProperty.js:253:23)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/ReadOnlyProperty.js:202:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 3/27/2024, 8:34:59 AM

----------------------------------

mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711550590569%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'valueProperty')
TypeError: Cannot read properties of undefined (reading 'valueProperty')
at valueProperty (BalancePointSceneModel.ts:182:35)
at regressLine (BalancePointSceneModel.ts:112:60)
at baseTimes (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:16095:20)
at times (BalancePointSceneModel.ts:112:10)
at listener (TinyEmitter.ts:213:6)
at notifyLoop (TinyEmitter.ts:185:17)
at emit (ReadOnlyProperty.ts:336:22)
at _notifyListeners (ReadOnlyProperty.ts:283:13)
at unguardedSet (ReadOnlyProperty.ts:267:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1711550099591%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711550590569%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1711550099591%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711550590569%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711550590569%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[PAGE ERROR] Error: TypeError: Cannot read properties of undefined (reading 'valueProperty')
at BalancePointSceneModel.regressLine (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/mean-share-and-balance/js/balance-point/model/BalancePointSceneModel.js:116:36)
at http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/mean-share-and-balance/js/balance-point/model/BalancePointSceneModel.js:72:60
at baseTimes (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:16095:20)
at http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/mean-share-and-balance/js/balance-point/model/BalancePointSceneModel.js:72:11
at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/ReadOnlyProperty.js:253:23)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/ReadOnlyProperty.js:202:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 3/27/2024, 8:34:59 AM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711550438819%7D&ea&brand=phet-io&phetioStandalone&fuzz
Query: ea&brand=phet-io&phetioStandalone&fuzz
Uncaught TypeError: Cannot read properties of undefined (reading 'valueProperty')
TypeError: Cannot read properties of undefined (reading 'valueProperty')
at valueProperty (BalancePointSceneModel.ts:182:35)
at regressLine (BalancePointSceneModel.ts:112:60)
at baseTimes (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:16095:20)
at times (BalancePointSceneModel.ts:112:10)
at listener (TinyEmitter.ts:213:6)
at notifyLoop (TinyEmitter.ts:185:17)
at emit (ReadOnlyProperty.ts:336:22)
at _notifyListeners (ReadOnlyProperty.ts:283:13)
at unguardedSet (ReadOnlyProperty.ts:267:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1711550099591%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711550438819%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1711550099591%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711550438819%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1711550099591%22%2C%22timestamp%22%3A1711550438819%7D&ea&brand=phet-io&phetioStandalone&fuzz
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[PAGE ERROR] Error: TypeError: Cannot read properties of undefined (reading 'valueProperty')
at BalancePointSceneModel.regressLine (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/mean-share-and-balance/js/balance-point/model/BalancePointSceneModel.js:116:36)
at http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/mean-share-and-balance/js/balance-point/model/BalancePointSceneModel.js:72:60
at baseTimes (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/sherpa/lib/lodash-4.17.4.js:16095:20)
at http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/mean-share-and-balance/js/balance-point/model/BalancePointSceneModel.js:72:11
at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/ReadOnlyProperty.js:253:23)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/ReadOnlyProperty.js:202:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1711550099591/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 3/27/2024, 8:34:59 AM
```

**Comment by marlitas** [comment]
I think this was fixed from a commit in a different issue. I'm not able to replicate locally after a 3 minute fuzz test, and I don't see it on CT from the last 40 columns. Closing.
