### ISSUE TITLE
CT reentry detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#22]
```
mean-share-and-balance : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653492277900/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653492277900%22%2C%22timestamp%22%3A1653497579124%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=-0.297725, oldValue=-0.5387500000000001
Error: Assertion failed: reentry detected, value=-0.297725, oldValue=-0.5387500000000001
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653492277900/assert/js/assert.js:28:13)
at assert (Property.ts:272:14)
at _notifyListeners (Property.ts:207:13)
at set (IntroModel.ts:234:31)
at Set.forEach
at forEach (IntroModel.ts:228:14)
at Array.forEach
at forEach (IntroModel.ts:226:24)
at levelWater (IntroModel.ts:256:9)
at step (Sim.ts:451:21)
id: Bayes Chrome
Snapshot from 5/25/2022, 9:24:37 AM
```

**Comment by marlitas** [comment]
Haven't seen this issue come up in CT since committing a fix on June 15th. Closing.
