### ISSUE TITLE
CT phetioMessageStack should be clear

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#28]
```
mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654760569833/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654760569833%22%2C%22timestamp%22%3A1654762192368%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioMessageStack should be clear
Error: Assertion failed: phetioMessageStack should be clear
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654760569833/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:636:16)
at listener (Timer.ts:33:10)
at (TinyEmitter.ts:108:42)
at emit (Sim.ts:960:24)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 1:42:49 AM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654760569833/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654760569833%22%2C%22timestamp%22%3A1654763347116%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioMessageStack should be clear
Error: Assertion failed: phetioMessageStack should be clear
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654760569833/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:636:16)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:94:8)
at emit (Sim.ts:960:24)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 1:42:49 AM
```

**Comment by marlitas** [comment]
Have not seen this issue come up on CT since switching to static allocation. Closing.
