### ISSUE TITLE
CT there should be a top snack available to set the fraction value

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#342]
```
mean-share-and-balance : fuzz : unbuilt
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723179169503%7D&brand=phet&ea&fuzz
ERROR: QUERY: brand=phet&ea&fuzz
Error: Assertion failed: there should be a top snack available to set the fraction value
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/assert/js/assert.js:45:13
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/assert/js/assert.js:45:13)
    at assert (FairShareModel.ts:116:16)
    at handleFraction (Plate.ts:276:34)
    at setNotepadSnacksToValue (Plate.ts:285:9)
    at syncNotepadToTable (SharingModel.ts:291:42)
    at forEach (SharingModel.ts:291:16)
    at syncData (SharingModel.ts:303:11)
    at resetData (FairShareModel.ts:577:10)
    at resetData (SharingModel.ts:326:9)
    at reset (MeanShareAndBalanceScreenView.ts:57:14)
    at  (TinyEmitter.ts:213:16)
    at notifyLoop (TinyEmitter.ts:196:13)
    at emit (Emitter.ts:64:21)
    at emit (PushButtonModel.ts:201:22)
    at fire (PushButtonModel.ts:143:15)
    at  (TinyEmitter.ts:213:16)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:343:22)
    at _notifyListeners (ReadOnlyProperty.ts:287:13)
    at unguardedSet (ReadOnlyProperty.ts:267:11)
    at set (Property.ts:65:10)
    at set (ButtonModel.ts:191:24)
    at  (TinyEmitter.ts:213:16)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:343:22)
    at _notifyListeners (ReadOnlyProperty.ts:287:13)
    at unguardedSet (ReadOnlyProperty.ts:267:11)
    at set (Property.ts:54:10)
    at  (PressListener.ts:754:4)
    at apply (PhetioAction.ts:162:16)
    at execute (PressListener.ts:512:24)
    at release (PressListener.ts:858:11)
    at inputEvent (Input.ts:1869:91)
    at dispatchToListeners (Input.ts:1818:9)
    at dispatchEvent (Input.ts:1622:9)
    at upEvent (Input.ts:396:11)
    at apply (PhetioAction.ts:162:16)
    at execute (Input.ts:1188:23)
    at mouseUp (InputFuzzer.js:275:26)
    at mouseToggle (InputFuzzer.js:40:11)
    at action (InputFuzzer.js:107:6)
    at fuzzEvents (SimDisplay.ts:221:23)
    at fuzzInputEvents (Sim.ts:1026:44)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1723178225427%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723179169503%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1723178225427%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723179169503%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723179169503%7D&brand=phet&ea&fuzz
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed:  there should be a top snack available to set the fraction value
[CONSOLE] Debug info: {
  "seed": 0.11322403761471822,
  "currentScreenName": "FairShareScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: there should be a top snack available to set the fraction value

id: "Sparky Node Firefox"
Snapshot from 8/8/2024, 10:37:05 PM

----------------------------------

mean-share-and-balance : fuzz : unbuilt : listenerOrderRandom
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723182035588%7D&brand=phet&ea&fuzz&listenerOrder=random
ERROR: QUERY: brand=phet&ea&fuzz&listenerOrder=random
Error: Assertion failed: there should be a top snack available to set the fraction value
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/assert/js/assert.js:45:13
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/assert/js/assert.js:45:13)
    at assert (FairShareModel.ts:116:16)
    at handleFraction (Plate.ts:276:34)
    at setNotepadSnacksToValue (Plate.ts:285:9)
    at syncNotepadToTable (SharingModel.ts:291:42)
    at forEach (SharingModel.ts:291:16)
    at syncData (SharingModel.ts:303:11)
    at resetData (FairShareModel.ts:577:10)
    at resetData (SharingModel.ts:326:9)
    at reset (MeanShareAndBalanceScreenView.ts:57:14)
    at  (TinyEmitter.ts:213:16)
    at notifyLoop (TinyEmitter.ts:196:13)
    at emit (Emitter.ts:64:21)
    at emit (PushButtonModel.ts:201:22)
    at fire (PushButtonModel.ts:143:15)
    at  (TinyEmitter.ts:213:16)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:343:22)
    at _notifyListeners (ReadOnlyProperty.ts:287:13)
    at unguardedSet (ReadOnlyProperty.ts:267:11)
    at set (Property.ts:65:10)
    at set (ButtonModel.ts:191:24)
    at  (TinyEmitter.ts:213:16)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:343:22)
    at _notifyListeners (ReadOnlyProperty.ts:287:13)
    at unguardedSet (ReadOnlyProperty.ts:267:11)
    at set (Property.ts:54:10)
    at  (PressListener.ts:754:4)
    at apply (PhetioAction.ts:162:16)
    at execute (PressListener.ts:512:24)
    at release (PressListener.ts:858:11)
    at inputEvent (Input.ts:1869:91)
    at dispatchToListeners (Input.ts:1818:9)
    at dispatchEvent (Input.ts:1622:9)
    at upEvent (Input.ts:513:13)
    at apply (PhetioAction.ts:162:16)
    at execute (Input.ts:1260:24)
    at touchEnd (InputFuzzer.js:242:24)
    at touchEnd (InputFuzzer.js:55:11)
    at action (InputFuzzer.js:107:6)
    at fuzzEvents (SimDisplay.ts:221:23)
    at fuzzInputEvents (Sim.ts:1026:44)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
    at requestAnimationFrame (Sim.ts:1018:11)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1723178225427%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723182035588%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1723178225427%2Fmean-share-and-balance%2Fmean-share-and-balance_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723182035588%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723182035588%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 97281
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed:  there should be a top snack available to set the fraction value
[CONSOLE] Debug info: {
  "seed": 0.30987807293825553,
  "currentScreenName": "FairShareScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: there should be a top snack available to set the fraction value

id: "Sparky Node Firefox"
Snapshot from 8/8/2024, 10:37:05 PM

----------------------------------

mean-share-and-balance : phet-io-multi-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/phet-io-wrappers/multi/?sim=mean-share-and-balance&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723181428697%7D
ERROR: Uncaught Error: Assertion failed: there should be a top snack available to set the fraction value
STACK: Error: Assertion failed: there should be a top snack available to set the fraction value
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/assert/js/assert.js:45:13)
    at assert (FairShareModel.ts:116:16)
    at handleFraction (Plate.ts:276:34)
    at setNotepadSnacksToValue (Plate.ts:285:9)
    at syncNotepadToTable (SharingModel.ts:291:42)
    at Array.forEach
    at forEach (SharingModel.ts:291:16)
    at syncData (SharingModel.ts:303:11)
    at resetData (FairShareModel.ts:577:10)
    at resetData (SharingModel.ts:326:9)
    at reset (MeanShareAndBalanceScreenView.ts:57:14)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:196:13)
    at emit (Emitter.ts:64:21)
    at emit (PushButtonModel.ts:201:22)
    at fire (PushButtonModel.ts:143:15)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:343:22)
    at _notifyListeners (ReadOnlyProperty.ts:287:13)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1723178225427%2Fphet-io-wrappers%2Fmulti%2F%3Fsim%3Dmean-share-and-balance%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=60000&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723181428697%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1723178225427%2Fphet-io-wrappers%2Fmulti%2F%3Fsim%3Dmean-share-and-balance%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=60000&testInfo=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723181428697%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/phet-io-wrappers/multi/?sim=mean-share-and-balance&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723181428697%7D
[ATTACHED] 
[NAVIGATED] about:blank
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/mean-share-and-balance/mean-share-and-balance_en.html?brand=phet-io&ea&postMessageOnError&sim=mean-share-and-balance&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723181428697%7D&frameTitle=sim1
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/mean-share-and-balance/mean-share-and-balance_en.html?brand=phet-io&ea&postMessageOnError&sim=mean-share-and-balance&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723178225427%22%2C%22timestamp%22%3A1723181428697%7D&frameTitle=sim2
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  there should be a top snack available to set the fraction value
[CONSOLE] Debug info: {
  "seed": 0.6150526015157087,
  "currentScreenName": "FairShareScreen"
}
[PAGE ERROR] Error: Error: Assertion failed: there should be a top snack available to set the fraction value
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/assert/js/assert.js:45:13)
    at Plate.handleFraction (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/fair-share/model/FairShareModel.js:97:17)
    at Plate.setNotepadSnacksToValue (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/Plate.js:213:35)
    at Plate.syncNotepadToTable (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/Plate.js:221:10)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/SharingModel.js:231:13
    at Array.forEach (<anonymous>)
    at FairShareModel.syncData (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/SharingModel.js:230:17)
    at FairShareModel.resetData (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/SharingModel.js:244:12)
    at FairShareModel.resetData (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/fair-share/model/FairShareModel.js:461:11)
    at FairShareModel.reset (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/SharingModel.js:269:10)
    at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/view/MeanShareAndBalanceScreenView.js:37:15)
    at TinyEmitter.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/TinyEmitter.js:161:14)
    at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/Emitter.js:52:22)
    at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/sun/js/buttons/PushButtonModel.js:145:23)
    at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
    at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/ReadOnlyProperty.js:254:23)
    at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
[CONSOLE] continuous-test-wrapper-load
[PAGE ERROR] Error: Error: Assertion failed: there should be a top snack available to set the fraction value
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/assert/js/assert.js:45:13)
    at Plate.handleFraction (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/fair-share/model/FairShareModel.js:97:17)
    at Plate.setNotepadSnacksToValue (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/Plate.js:213:35)
    at Plate.syncNotepadToTable (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/Plate.js:221:10)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/SharingModel.js:231:13
    at Array.forEach (<anonymous>)
    at FairShareModel.syncData (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/SharingModel.js:230:17)
    at FairShareModel.resetData (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/SharingModel.js:244:12)
    at FairShareModel.resetData (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/fair-share/model/FairShareModel.js:461:11)
    at FairShareModel.reset (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/model/SharingModel.js:269:10)
    at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/mean-share-and-balance/js/common/view/MeanShareAndBalanceScreenView.js:37:15)
    at TinyEmitter.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/TinyEmitter.js:161:14)
    at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/Emitter.js:52:22)
    at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/sun/js/buttons/PushButtonModel.js:145:23)
    at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
    at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/ReadOnlyProperty.js:254:23)
    at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1723178225427/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 8/8/2024, 10:37:05 PM
```

**Comment by KatieWoe** [comment]
I haven't seen this while fuzzing the debug version of the sim
