### ISSUE TITLE
CT Assertion failed: index out of bounds: 0, array length is 0

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#37]
@samreid and I attempted to trace this through iframe API test, but the error is not consistent enough for iteration. Added asserts in IntroModel.ts with the hopes that CT will catch on next round.

```
mean-share-and-balance : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true
103 out of 104 tests passed. 1 failed.
SimTests: mean-share-and-balance: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: index out of bounds: 0, array length is 0
Error: Assertion failed: index out of bounds: 0, array length is 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/assert/js/assert.js:28:13)
at PhetioGroup.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/tandem/js/PhetioGroup.js:123:15)
at IntroModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/mean-share-and-balance/js/intro/model/IntroModel.js:208:42)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/joist/js/Sim.js:299:22
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/tandem/js/PhetioAction.js:91:17)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/joist/js/Sim.js:766:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/joist/js/Sim.js:755:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/joist/js/Sim.js:733:12)

Uncaught Error: Uncaught Error: Assertion failed: index out of bounds: 0, array length is 0Error: Assertion failed: index out of bounds: 0, array length is 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/assert/js/assert.js:28:13)
at assert (PhetioGroup.ts:143:14)
at getElement (IntroModel.ts:240:41)
at step (Sim.ts:447:21)
at apply (PhetioAction.ts:125:16)
at execute (Sim.ts:990:30)
at stepSimulation (Sim.ts:980:11)
at stepOneFrame (Sim.ts:955:11)
id: Bayes Puppeteer
Snapshot from 6/16/2022, 7:09:28 PM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance
101 out of 102 tests passed. 1 failed.
SimTests: mean-share-and-balance: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: index out of bounds: 0, array length is 0
Error: Assertion failed: index out of bounds: 0, array length is 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/assert/js/assert.js:28:13)
at PhetioGroup.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/tandem/js/PhetioGroup.js:123:15)
at IntroModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/mean-share-and-balance/js/intro/model/IntroModel.js:208:42)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/joist/js/Sim.js:299:22
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/tandem/js/PhetioAction.js:91:17)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/joist/js/Sim.js:766:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/joist/js/Sim.js:755:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/chipper/dist/js/joist/js/Sim.js:733:12)

Uncaught Error: Uncaught Error: Assertion failed: index out of bounds: 0, array length is 0Error: Assertion failed: index out of bounds: 0, array length is 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655428168890/assert/js/assert.js:28:13)
at assert (PhetioGroup.ts:143:14)
at getElement (IntroModel.ts:240:41)
at step (Sim.ts:447:21)
at apply (PhetioAction.ts:125:16)
at execute (Sim.ts:990:30)
at stepSimulation (Sim.ts:980:11)
at stepOneFrame (Sim.ts:955:11)
id: Bayes Puppeteer
Snapshot from 6/16/2022, 7:09:28 PM
```

**Comment by zepumph** [comment]
I didn't poke around long enough, but even so, I believe I still have a theory.  @samreid and I spoke about this, and to me it seems to be related to the patch in this issue:

https://github.com/phetsims/mean-share-and-balance/issues/20

Here we moved logic from a listener on the countProperty to listenting to when the 3d group changes (for the 2d group and pipe group). Then PhET-iO state will be set up to call all the needed logic because the code will always fire. Right now, the listener doesn't fire if setting state from 3 -> 3, because the value didn't change, but the groups were cleared and recreated so the listener logic still needs to rechurn. Next steps here are for an hour long pairing session with @samreid and @zepumph sometime when SR is back from vacation.

**Comment by samreid** [comment]
We think this was fixed after we abandoned PhetioGroup, closing.
