### ISSUE TITLE
CT Total 2D and 3D water should be equal

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#81]
```
mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1657157639768%22%2C%22timestamp%22%3A1657160535242%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 0.0980196844362709 3D Water: 5.551115123125783e-17
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 0.0980196844362709 3D Water: 5.551115123125783e-17
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (IntroModel.ts:393:14)
at changeWaterLevel (WaterCup3DNode.ts:85:19)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:259:22)
at _notifyListeners (ReadOnlyProperty.ts:210:13)
at set (Property.ts:67:10)
at set (Slider.ts:423:24)
at _dragListener (PressListener.ts:527:9)
at call (DragListener.ts:308:35)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM

----------------------------------

mean-share-and-balance : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1657157639768%22%2C%22timestamp%22%3A1657166380471%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 0 3D Water: 0.37544406857142865
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 0 3D Water: 0.37544406857142865
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (IntroModel.ts:393:14)
at changeWaterLevel (WaterCup3DNode.ts:85:19)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:259:22)
at _notifyListeners (ReadOnlyProperty.ts:210:13)
at set (Property.ts:67:10)
at set (Slider.ts:423:24)
at _dragListener (PressListener.ts:527:9)
at call (DragListener.ts:308:35)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1657157639768%22%2C%22timestamp%22%3A1657161045804%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:299:16)
at assertDynamicPhetioObject (PhetioDynamicElementContainer.ts:288:19)
at createDynamicElement (PhetioGroup.ts:273:30)
at createIndexedElement (PhetioGroup.ts:244:16)
at createNextElement (LevelingOutModel.ts:63:33)
at (LevelingOutScreen.ts:32:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:838:15)
at (Sim.ts:849:10)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1657157639768%22%2C%22timestamp%22%3A1657166883572%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:299:16)
at assertDynamicPhetioObject (PhetioDynamicElementContainer.ts:288:19)
at createDynamicElement (PhetioGroup.ts:273:30)
at createIndexedElement (PhetioGroup.ts:244:16)
at createNextElement (LevelingOutModel.ts:63:33)
at (LevelingOutScreen.ts:32:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:838:15)
at (Sim.ts:849:10)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1657157639768%22%2C%22timestamp%22%3A1657172424897%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:299:16)
at assertDynamicPhetioObject (PhetioDynamicElementContainer.ts:288:19)
at createDynamicElement (PhetioGroup.ts:273:30)
at createIndexedElement (PhetioGroup.ts:244:16)
at createNextElement (LevelingOutModel.ts:63:33)
at (LevelingOutScreen.ts:32:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:838:15)
at (Sim.ts:849:10)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1657157639768%22%2C%22timestamp%22%3A1657179720690%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:299:16)
at assertDynamicPhetioObject (PhetioDynamicElementContainer.ts:288:19)
at createDynamicElement (PhetioGroup.ts:273:30)
at createIndexedElement (PhetioGroup.ts:244:16)
at createNextElement (LevelingOutModel.ts:63:33)
at (LevelingOutScreen.ts:32:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:838:15)
at (Sim.ts:849:10)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1657157639768%22%2C%22timestamp%22%3A1657160722311%7D
Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:299:16)
at assertDynamicPhetioObject (PhetioDynamicElementContainer.ts:288:19)
at createDynamicElement (PhetioGroup.ts:273:30)
at createIndexedElement (PhetioGroup.ts:244:16)
at createNextElement (LevelingOutModel.ts:63:33)
at (LevelingOutScreen.ts:32:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:838:15)
at (Sim.ts:849:10)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1657157639768%22%2C%22timestamp%22%3A1657167023109%7D
Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:299:16)
at assertDynamicPhetioObject (PhetioDynamicElementContainer.ts:288:19)
at createDynamicElement (PhetioGroup.ts:273:30)
at createIndexedElement (PhetioGroup.ts:244:16)
at createNextElement (LevelingOutModel.ts:63:33)
at (LevelingOutScreen.ts:32:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:838:15)
at (Sim.ts:849:10)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1657157639768%22%2C%22timestamp%22%3A1657172402835%7D
Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:299:16)
at assertDynamicPhetioObject (PhetioDynamicElementContainer.ts:288:19)
at createDynamicElement (PhetioGroup.ts:273:30)
at createIndexedElement (PhetioGroup.ts:244:16)
at createNextElement (LevelingOutModel.ts:63:33)
at (LevelingOutScreen.ts:32:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:838:15)
at (Sim.ts:849:10)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1657157639768%22%2C%22timestamp%22%3A1657179918519%7D
Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:299:16)
at assertDynamicPhetioObject (PhetioDynamicElementContainer.ts:288:19)
at createDynamicElement (PhetioGroup.ts:273:30)
at createIndexedElement (PhetioGroup.ts:244:16)
at createNextElement (LevelingOutModel.ts:63:33)
at (LevelingOutScreen.ts:32:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:838:15)
at (Sim.ts:849:10)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true
27 out of 28 tests passed. 1 failed.
SimTests: mean-share-and-balance: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at PhetioGroup.assertDynamicPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/tandem/js/PhetioDynamicElementContainer.js:238:17)
at PhetioGroup.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/tandem/js/PhetioDynamicElementContainer.js:227:20)
at PhetioGroup.createIndexedElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/tandem/js/PhetioGroup.js:261:31)
at PhetioGroup.createNextElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/tandem/js/PhetioGroup.js:237:17)
at new LevelingOutModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/mean-share-and-balance/js/leveling-out/model/LevelingOutModel.js:46:34)
at LevelingOutScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/mean-share-and-balance/js/leveling-out/LevelingOutScreen.js:22:17)
at LevelingOutScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/joist/js/Screen.js:197:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/joist/js/Sim.js:628:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/joist/js/Sim.js:638:21

Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:trueError: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:299:16)
at assertDynamicPhetioObject (PhetioDynamicElementContainer.ts:288:19)
at createDynamicElement (PhetioGroup.ts:273:30)
at createIndexedElement (PhetioGroup.ts:244:16)
at createNextElement (LevelingOutModel.ts:63:33)
at (LevelingOutScreen.ts:32:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:838:15)
at (Sim.ts:849:10)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance
25 out of 26 tests passed. 1 failed.
SimTests: mean-share-and-balance: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at PhetioGroup.assertDynamicPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/tandem/js/PhetioDynamicElementContainer.js:238:17)
at PhetioGroup.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/tandem/js/PhetioDynamicElementContainer.js:227:20)
at PhetioGroup.createIndexedElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/tandem/js/PhetioGroup.js:261:31)
at PhetioGroup.createNextElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/tandem/js/PhetioGroup.js:237:17)
at new LevelingOutModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/mean-share-and-balance/js/leveling-out/model/LevelingOutModel.js:46:34)
at LevelingOutScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/mean-share-and-balance/js/leveling-out/LevelingOutScreen.js:22:17)
at LevelingOutScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/joist/js/Screen.js:197:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/joist/js/Sim.js:628:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/chipper/dist/js/joist/js/Sim.js:638:21

Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:trueError: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1657157639768/assert/js/assert.js:28:13)
at assert (PhetioDynamicElementContainer.ts:299:16)
at assertDynamicPhetioObject (PhetioDynamicElementContainer.ts:288:19)
at createDynamicElement (PhetioGroup.ts:273:30)
at createIndexedElement (PhetioGroup.ts:244:16)
at createNextElement (LevelingOutModel.ts:63:33)
at (LevelingOutScreen.ts:32:12)
at createModel (Screen.ts:276:23)
at initializeModel (Sim.ts:838:15)
at (Sim.ts:849:10)
id: Bayes Puppeteer
Snapshot from 7/6/2022, 7:33:59 PM
```

**Comment by marlitas** [comment]
It appears this error is no longer happening in CT. closing.
