### ISSUE TITLE
CT required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#84]
```
mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658156886162%22%2C%22timestamp%22%3A1658161882907%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:206:16)
at initializePhetioObject (PhetioObject.ts:178:11)
at (PhetioDataHandler.ts:101:4)
at (PhetioAction.ts:83:4)
at (PressListener.ts:336:24)
at (FireListener.ts:63:4)
at (IntroScreenView.ts:124:33)
at (IntroScreen.ts:33:15)
at createView (Screen.ts:290:22)
id: Bayes Puppeteer
Snapshot from 7/18/2022, 9:08:06 AM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658156886162%22%2C%22timestamp%22%3A1658161323647%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:206:16)
at initializePhetioObject (PhetioObject.ts:178:11)
at (PhetioDataHandler.ts:101:4)
at (PhetioAction.ts:83:4)
at (PressListener.ts:336:24)
at (FireListener.ts:63:4)
at (IntroScreenView.ts:124:33)
at (IntroScreen.ts:33:15)
at createView (Screen.ts:290:22)
id: Bayes Puppeteer
Snapshot from 7/18/2022, 9:08:06 AM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true
27 out of 28 tests passed. 1 failed.
SimTests: mean-share-and-balance: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/assert/js/assert.js:28:13)
at PhetioAction.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/tandem/js/PhetioObject.js:143:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/tandem/js/PhetioObject.js:116:12)
at new PhetioDataHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/tandem/js/PhetioDataHandler.js:65:5)
at new PhetioAction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/tandem/js/PhetioAction.js:56:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/scenery/js/listeners/PressListener.js:170:25)
at new FireListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/scenery/js/listeners/FireListener.js:35:5)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/mean-share-and-balance/js/intro/view/IntroScreenView.js:111:34)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/mean-share-and-balance/js/intro/IntroScreen.js:24:18)
at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/joist/js/Screen.js:211:23)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:206:16)
at initializePhetioObject (PhetioObject.ts:178:11)
at (PhetioDataHandler.ts:101:4)
at (PhetioAction.ts:83:4)
at (PressListener.ts:336:24)
at (FireListener.ts:63:4)
at (IntroScreenView.ts:124:33)
at (IntroScreen.ts:33:15)
at createView (Screen.ts:290:22)
id: Bayes Puppeteer
Snapshot from 7/18/2022, 9:08:06 AM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance
25 out of 26 tests passed. 1 failed.
SimTests: mean-share-and-balance: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/assert/js/assert.js:28:13)
at PhetioAction.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/tandem/js/PhetioObject.js:143:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/tandem/js/PhetioObject.js:116:12)
at new PhetioDataHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/tandem/js/PhetioDataHandler.js:65:5)
at new PhetioAction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/tandem/js/PhetioAction.js:56:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/scenery/js/listeners/PressListener.js:170:25)
at new FireListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/scenery/js/listeners/FireListener.js:35:5)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/mean-share-and-balance/js/intro/view/IntroScreenView.js:111:34)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/mean-share-and-balance/js/intro/IntroScreen.js:24:18)
at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/chipper/dist/js/joist/js/Screen.js:211:23)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:206:16)
at initializePhetioObject (PhetioObject.ts:178:11)
at (PhetioDataHandler.ts:101:4)
at (PhetioAction.ts:83:4)
at (PressListener.ts:336:24)
at (FireListener.ts:63:4)
at (IntroScreenView.ts:124:33)
at (IntroScreen.ts:33:15)
at createView (Screen.ts:290:22)
id: Bayes Puppeteer
Snapshot from 7/18/2022, 9:08:06 AM
```

**Comment by marlitas** [comment]
I haven't seen this error come up for a while, so closing.
