### ISSUE TITLE
CT reentry detected, value=true, oldValue=false

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#85]
```
mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658463065036%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=true, oldValue=false
Error: Assertion failed: reentry detected, value=true, oldValue=false
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:258:14)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (Pipe.ts:69:26)
at reset (Pipe.ts:64:66)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658470105334%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Expected 2 cups, but found: 1.
Error: Assertion failed: Expected 2 cups, but found: 1.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (IntroModel.ts:291:14)
at assertConsistentState (IntroModel.ts:267:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:980:30)
at stepSimulation (Sim.ts:970:11)
at stepOneFrame (Sim.ts:945:11)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658486625810%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=true, oldValue=false
Error: Assertion failed: reentry detected, value=true, oldValue=false
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:258:14)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (Pipe.ts:69:26)
at reset (Pipe.ts:64:66)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658468067900%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=true, oldValue=false
Error: Assertion failed: reentry detected, value=true, oldValue=false
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:258:14)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (Pipe.ts:69:26)
at reset (Pipe.ts:64:66)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658483176011%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 1 3D Water: 1.25
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 1 3D Water: 1.25
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (IntroModel.ts:365:14)
at changeWaterLevel (WaterCup3DNode.ts:85:8)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (NumberProperty.ts:178:10)
at reset (WaterCup3DNode.ts:89:66)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658463019670%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: Expected 7 cups, but found: 1.
Error: Assertion failed: Expected 7 cups, but found: 1.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (IntroModel.ts:291:14)
at assertConsistentState (IntroModel.ts:267:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:980:30)
at stepSimulation (Sim.ts:970:11)
at stepOneFrame (Sim.ts:945:11)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658471171630%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: Expected 2 cups, but found: 1.
Error: Assertion failed: Expected 2 cups, but found: 1.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (IntroModel.ts:291:14)
at assertConsistentState (IntroModel.ts:267:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:980:30)
at stepSimulation (Sim.ts:970:11)
at stepOneFrame (Sim.ts:945:11)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658487842107%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: Expected 2 cups, but found: 1.
Error: Assertion failed: Expected 2 cups, but found: 1.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (IntroModel.ts:291:14)
at assertConsistentState (IntroModel.ts:267:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:980:30)
at stepSimulation (Sim.ts:970:11)
at stepOneFrame (Sim.ts:945:11)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658471628812%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 1 3D Water: 1.25
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 1 3D Water: 1.25
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (IntroModel.ts:365:14)
at changeWaterLevel (WaterCup3DNode.ts:85:8)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (NumberProperty.ts:178:10)
at reset (WaterCup3DNode.ts:89:66)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658463839237%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=true, oldValue=false
Error: Assertion failed: reentry detected, value=true, oldValue=false
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:258:14)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (Pipe.ts:69:26)
at reset (Pipe.ts:64:66)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658471383476%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 1 3D Water: 1.25
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 1 3D Water: 1.25
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (IntroModel.ts:365:14)
at changeWaterLevel (WaterCup3DNode.ts:85:8)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (NumberProperty.ts:178:10)
at reset (WaterCup3DNode.ts:89:66)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658464081590%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Expected 2 cups, but found: 1.
Error: Assertion failed: Expected 2 cups, but found: 1.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (IntroModel.ts:291:14)
at assertConsistentState (IntroModel.ts:267:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:980:30)
at stepSimulation (Sim.ts:970:11)
at stepOneFrame (Sim.ts:945:11)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658470871374%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: reentry detected, value=true, oldValue=false
Error: Assertion failed: reentry detected, value=true, oldValue=false
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:258:14)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (Pipe.ts:69:26)
at reset (Pipe.ts:64:66)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658487822004%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 1 3D Water: 1.25
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 1 3D Water: 1.25
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (IntroModel.ts:365:14)
at changeWaterLevel (WaterCup3DNode.ts:85:8)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (NumberProperty.ts:178:10)
at reset (WaterCup3DNode.ts:89:66)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658463426112%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: reentry detected, value=true, oldValue=false
Error: Assertion failed: reentry detected, value=true, oldValue=false
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:258:14)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (Pipe.ts:69:26)
at reset (Pipe.ts:64:66)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658473111563%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Cannot fire when already firing
Error: Assertion failed: Cannot fire when already firing
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (PushButtonModel.ts:177:14)
at (CallbackTimer.ts:129:6)
at fire (CallbackTimer.ts:105:13)
at stop (PushButtonModel.ts:115:21)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (ButtonModel.ts:187:24)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658474768165%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=true, oldValue=false
Error: Assertion failed: reentry detected, value=true, oldValue=false
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:258:14)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (Pipe.ts:69:26)
at reset (Pipe.ts:64:66)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

mean-share-and-balance : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1658457063507%22%2C%22timestamp%22%3A1658488477332%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=true, oldValue=false
Error: Assertion failed: reentry detected, value=true, oldValue=false
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:258:14)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:65:10)
at set (Property.ts:58:9)
at reset (Pipe.ts:69:26)
at reset (Pipe.ts:64:66)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM
```

**Comment by marlitas** [comment]
Fixed in above commit. Closing.
