### ISSUE TITLE
Debug Console Error

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#89]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Firefox and Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/821
When running a fuzz test in the debug version of the sim, this console error appeared and continued to appear with a frozen sim. I'm not sure how it occurred, but the error seems to indicate trying to add and/or remove a cup at the same time.

**Visuals**
<img width="959" alt="bugchrome" src="https://user-images.githubusercontent.com/41024075/181122786-dcb51191-b282-4df1-b2b8-022884753a4e.png">
<img width="960" alt="debugfire" src="https://user-images.githubusercontent.com/41024075/181122790-2342c3ed-465f-4314-a666-0e484762880f.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.6/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.6 2022-07-26 18:07:52 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
I have been unable to recreate this on my local machine using the query params: `debugger` and `fuzz`. It may be that I coincidentally fixed it in a different bug fix commit. However I'm not honestly sure what changes I did would have fixed a cup removal or addition bug. 

I will keep an eye out for this the next few days, and this assertion should come up on CT as well if it is still there.

**Comment by marlitas** [comment]
It looks like this error is not coming up on CT either. Closing.

**Comment by KatieWoe** [comment]
I am seeing this in CT
```
mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659117960664%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Expected 7 cups, but found: 6.
Error: Assertion failed: Expected 7 cups, but found: 6.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/assert/js/assert.js:28:13)
at assert (IntroModel.ts:301:14)
at assertConsistentState (IntroModel.ts:278:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:982:30)
at stepSimulation (Sim.ts:972:11)
at stepOneFrame (Sim.ts:947:11)
id: Bayes Puppeteer
Snapshot from 7/29/2022, 10:22:05 AM

----------------------------------

mean-share-and-balance : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659119203465%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: Expected 7 cups, but found: 1.
Error: Assertion failed: Expected 7 cups, but found: 1.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/assert/js/assert.js:28:13)
at assert (IntroModel.ts:301:14)
at assertConsistentState (IntroModel.ts:278:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:982:30)
at stepSimulation (Sim.ts:972:11)
at stepOneFrame (Sim.ts:947:11)
id: Bayes Puppeteer
Snapshot from 7/29/2022, 10:22:05 AM

----------------------------------

mean-share-and-balance : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659123986656%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: Expected 7 cups, but found: 1.
Error: Assertion failed: Expected 7 cups, but found: 1.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/assert/js/assert.js:28:13)
at assert (IntroModel.ts:301:14)
at assertConsistentState (IntroModel.ts:278:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:982:30)
at stepSimulation (Sim.ts:972:11)
at stepOneFrame (Sim.ts:947:11)
id: Bayes Puppeteer
Snapshot from 7/29/2022, 10:22:05 AM

----------------------------------

mean-share-and-balance : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659124023616%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: Expected 7 cups, but found: 6.
Error: Assertion failed: Expected 7 cups, but found: 6.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/assert/js/assert.js:28:13)
at assert (IntroModel.ts:301:14)
at assertConsistentState (IntroModel.ts:278:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:982:30)
at stepSimulation (Sim.ts:972:11)
at stepOneFrame (Sim.ts:947:11)
id: Bayes Puppeteer
Snapshot from 7/29/2022, 10:22:05 AM

----------------------------------

mean-share-and-balance : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659123193042%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'waterLevelProperty')
TypeError: Cannot read properties of undefined (reading 'waterLevelProperty')
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659123193042%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1417877)
at vD.iterateCups (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659123193042%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1417717)
at vD.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659123193042%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1417838)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659123193042%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1401939)
at ul.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659123193042%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:557309)
at eD.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659123193042%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1409595)
at eD.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659123193042%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1409533)
at eD.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659123193042%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1409263)
id: Bayes Puppeteer
Snapshot from 7/29/2022, 10:22:05 AM

----------------------------------

mean-share-and-balance : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659124069532%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'waterLevelProperty')
TypeError: Cannot read properties of undefined (reading 'waterLevelProperty')
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659124069532%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1417877)
at vD.iterateCups (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659124069532%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1417717)
at vD.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659124069532%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1417838)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659124069532%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1401939)
at ul.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659124069532%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:557309)
at eD.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659124069532%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1409595)
at eD.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659124069532%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1409533)
at eD.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/build/phet/mean-share-and-balance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659124069532%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1409263)
id: Bayes Puppeteer
Snapshot from 7/29/2022, 10:22:05 AM

----------------------------------

mean-share-and-balance : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659117693265%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: Expected 7 cups, but found: 2.
Error: Assertion failed: Expected 7 cups, but found: 2.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/assert/js/assert.js:28:13)
at assert (IntroModel.ts:301:14)
at assertConsistentState (IntroModel.ts:278:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:982:30)
at stepSimulation (Sim.ts:972:11)
at stepOneFrame (Sim.ts:947:11)
id: Bayes Puppeteer
Snapshot from 7/29/2022, 10:22:05 AM

----------------------------------

mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659119052227%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Expected 7 cups, but found: 6.
Error: Assertion failed: Expected 7 cups, but found: 6.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/assert/js/assert.js:28:13)
at assert (IntroModel.ts:301:14)
at assertConsistentState (IntroModel.ts:278:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:982:30)
at stepSimulation (Sim.ts:972:11)
at stepOneFrame (Sim.ts:947:11)
id: Bayes Puppeteer
Snapshot from 7/29/2022, 10:22:05 AM

----------------------------------

mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659111725024%22%2C%22timestamp%22%3A1659123782824%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Expected 7 cups, but found: 6.
Error: Assertion failed: Expected 7 cups, but found: 6.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659111725024/assert/js/assert.js:28:13)
at assert (IntroModel.ts:301:14)
at assertConsistentState (IntroModel.ts:278:9)
at step (Sim.ts:438:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:982:30)
at stepSimulation (Sim.ts:972:11)
at stepOneFrame (Sim.ts:947:11)
id: Bayes Puppeteer
Snapshot from 7/29/2022, 10:22:05 AM
```
