### ISSUE TITLE
CT Total 2D and 3D water should be equal

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#92]
```
mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659593317029%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.7013122158388576 3D Water: 3.166666664291978
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.7013122158388576 3D Water: 3.166666664291978
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659601735075%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.4954545454545456 3D Water: 3.490909090909091
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.4954545454545456 3D Water: 3.490909090909091
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659610924730%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.96875 3D Water: 4
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.96875 3D Water: 4
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659608949191%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.6464337548476564 3D Water: 3.75
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.6464337548476564 3D Water: 3.75
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659593274974%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 4.04 3D Water: 4.29
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 4.04 3D Water: 4.29
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659611851276%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.95 3D Water: 4.45
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.95 3D Water: 4.45
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659593909714%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.506818181818182 3D Water: 3.513636363636364
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.506818181818182 3D Water: 3.513636363636364
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659599693604%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.7370833333333335 3D Water: 3.75
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.7370833333333335 3D Water: 3.75
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659613352064%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.65 3D Water: 4
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.65 3D Water: 4
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659594407359%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: Expected 2 cups, but found: 1.
Error: Assertion failed: Expected 2 cups, but found: 1.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:279:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659599887144%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Unloaded frame before complete, window.location probably changed
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659610860046%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.4250625 3D Water: 3
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.4250625 3D Water: 3
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659599782853%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 2.8709379355298594 3D Water: 2.5
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 2.8709379355298594 3D Water: 2.5
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659611302206%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.6820500000000003 3D Water: 3.75
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.6820500000000003 3D Water: 3.75
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659594936379%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.6068200230736496 3D Water: 3.659090909090909
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.6068200230736496 3D Water: 3.659090909090909
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659599910401%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.625 3D Water: 3.75
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.625 3D Water: 3.75
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659611454551%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3 3D Water: 3.4491444769020037
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3 3D Water: 3.4491444769020037
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659594202090%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.74125 3D Water: 3.75
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 3.74125 3D Water: 3.75
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM

----------------------------------

mean-share-and-balance : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1659587369389%22%2C%22timestamp%22%3A1659603530453%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 2.999475201 3D Water: 2.5
Error: Assertion failed: Total 2D and 3D water should be equal. 2D Water: 2.999475201 3D Water: 2.5
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659587369389/assert/js/assert.js:28:13)
at assert (IntroModel.ts:288:14)
at assertConsistentState (IntroModel.ts:270:9)
at step (Sim.ts:445:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1004:30)
at stepSimulation (Sim.ts:994:11)
at stepOneFrame (Sim.ts:969:11)
id: Bayes Puppeteer
Snapshot from 8/3/2022, 10:29:29 PM
```

**Comment by marlitas** [comment]
This is associated with changes for: https://github.com/phetsims/mean-share-and-balance/issues/90

**Comment by marlitas** [comment]
It's looking like some fixes we implemented at the end of last week for https://github.com/phetsims/mean-share-and-balance/issues/90 are working. Not seeing this error in CT anymore. Closing.
