### ISSUE TITLE
CT phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#95]
```
mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660820371948%22%2C%22timestamp%22%3A1660825707311%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:658:35)
at phetioObjectAdded (phetioEngine.ts:1223:19)
at addPhetioObject (Tandem.ts:190:37)
at addPhetioObject (PhetioObject.ts:335:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Node.ts:825:11)
at (ValveNode.ts:54:4)
at (IntroScreenView.ts:124:12)
id: Bayes Puppeteer
Snapshot from 8/18/2022, 4:59:31 AM

----------------------------------

mean-share-and-balance : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/mean-share-and-balance/mean-share-and-balance_en.html?continuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660820371948%22%2C%22timestamp%22%3A1660831512016%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:658:35)
at phetioObjectAdded (phetioEngine.ts:1223:19)
at addPhetioObject (Tandem.ts:190:37)
at addPhetioObject (PhetioObject.ts:335:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Node.ts:825:11)
at (ValveNode.ts:54:4)
at (IntroScreenView.ts:124:12)
id: Bayes Puppeteer
Snapshot from 8/18/2022, 4:59:31 AM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660820371948%22%2C%22timestamp%22%3A1660825438099%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:658:35)
at phetioObjectAdded (phetioEngine.ts:1223:19)
at addPhetioObject (Tandem.ts:190:37)
at addPhetioObject (PhetioObject.ts:335:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Node.ts:825:11)
at (ValveNode.ts:54:4)
at (IntroScreenView.ts:124:12)
id: Bayes Puppeteer
Snapshot from 8/18/2022, 4:59:31 AM

----------------------------------

mean-share-and-balance : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/phet-io-wrappers/state/?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22mean-share-and-balance%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660820371948%22%2C%22timestamp%22%3A1660831747490%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:658:35)
at phetioObjectAdded (phetioEngine.ts:1223:19)
at addPhetioObject (Tandem.ts:190:37)
at addPhetioObject (PhetioObject.ts:335:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Node.ts:825:11)
at (ValveNode.ts:54:4)
at (IntroScreenView.ts:124:12)
id: Bayes Puppeteer
Snapshot from 8/18/2022, 4:59:31 AM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance&phetioDebug=true&phetioWrapperDebug=true
32 out of 33 tests passed. 1 failed.
SimTests: mean-share-and-balance: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/assert/js/assert.js:28:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/phet-io/js/phetioEngine.js:583:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/phet-io/js/phetioEngine.js:1041:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/tandem/js/Tandem.js:143:36)
at ValveNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/tandem/js/PhetioObject.js:265:17)
at ValveNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/scenery/js/nodes/Node.js:6368:11)
at ValveNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/scenery/js/nodes/Node.js:6358:10)
at new Node (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/scenery/js/nodes/Node.js:519:12)
at new ValveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/mean-share-and-balance/js/intro/view/ValveNode.js:46:5)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/mean-share-and-balance/js/intro/view/IntroScreenView.js:96:145)

Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNodeError: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:658:35)
at phetioObjectAdded (phetioEngine.ts:1223:19)
at addPhetioObject (Tandem.ts:190:37)
at addPhetioObject (PhetioObject.ts:335:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Node.ts:825:11)
at (ValveNode.ts:54:4)
at (IntroScreenView.ts:124:12)
id: Bayes Puppeteer
Snapshot from 8/18/2022, 4:59:31 AM

----------------------------------

mean-share-and-balance : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/phet-io-wrappers/phet-io-wrappers-tests.html?sim=mean-share-and-balance
30 out of 31 tests passed. 1 failed.
SimTests: mean-share-and-balance: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/assert/js/assert.js:28:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/phet-io/js/phetioEngine.js:583:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/phet-io/js/phetioEngine.js:1041:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/tandem/js/Tandem.js:143:36)
at ValveNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/tandem/js/PhetioObject.js:265:17)
at ValveNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/scenery/js/nodes/Node.js:6368:11)
at ValveNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/scenery/js/nodes/Node.js:6358:10)
at new Node (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/scenery/js/nodes/Node.js:519:12)
at new ValveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/mean-share-and-balance/js/intro/view/ValveNode.js:46:5)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/chipper/dist/js/mean-share-and-balance/js/intro/view/IntroScreenView.js:96:145)

Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNodeError: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660820371948/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:658:35)
at phetioObjectAdded (phetioEngine.ts:1223:19)
at addPhetioObject (Tandem.ts:190:37)
at addPhetioObject (PhetioObject.ts:335:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Node.ts:825:11)
at (ValveNode.ts:54:4)
at (IntroScreenView.ts:124:12)
id: Bayes Puppeteer
Snapshot from 8/18/2022, 4:59:31 AM
```

**Comment by marlitas** [comment]
Fixed. Closing.
